version: '2'
services:
  web:
    build: .
    command: 'python3 manage.py runserver 0.0.0.0:8000 --settings=Kases.settings  --configuration=Dev'
    volumes:
      - .:/code
    ports:
      - "8000:8000"
