# Generated by Django 2.0.3 on 2018-08-12 04:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0011_auto_20180812_1443'),
        ('case', '0013_auto_20180812_1351'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalLoan',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('description', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Description')),
                ('created', models.DateTimeField(editable=False, verbose_name='Creation date and time')),
                ('modified', models.DateTimeField(editable=False, null=True, verbose_name='Modification date and time')),
                ('private', models.BooleanField(default=False, verbose_name='Private')),
                ('reason', models.TextField(max_length=1000, verbose_name='Reason')),
                ('booked_from', models.TextField(max_length=100, verbose_name='Booked From')),
                ('booked_until', models.TextField(max_length=100, verbose_name='Booked Until')),
                ('condition', models.CharField(choices=[('NW', 'New'), ('EX', 'Excellent'), ('GD', 'Good'), ('AV', 'Average'), ('BA', 'Below Average'), ('PR', 'Poor'), ('DM', 'Damaged'), ('LO', 'Lost')], default='EX', max_length=2, verbose_name='Device Condition')),
                ('returned', models.BooleanField(default=False, verbose_name='Returned')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('case', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='case.Case')),
                ('device', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.Device')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('loaned_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('loaned_to', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Device Loan',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Description')),
                ('created', models.DateTimeField(editable=False, verbose_name='Creation date and time')),
                ('modified', models.DateTimeField(editable=False, null=True, verbose_name='Modification date and time')),
                ('private', models.BooleanField(default=False, verbose_name='Private')),
                ('reason', models.TextField(max_length=1000, verbose_name='Reason')),
                ('booked_from', models.TextField(max_length=100, verbose_name='Booked From')),
                ('booked_until', models.TextField(max_length=100, verbose_name='Booked Until')),
                ('condition', models.CharField(choices=[('NW', 'New'), ('EX', 'Excellent'), ('GD', 'Good'), ('AV', 'Average'), ('BA', 'Below Average'), ('PR', 'Poor'), ('DM', 'Damaged'), ('LO', 'Lost')], default='EX', max_length=2, verbose_name='Device Condition')),
                ('returned', models.BooleanField(default=False, verbose_name='Returned')),
                ('case', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='loan_case', to='case.Case', verbose_name='Case')),
                ('device', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='loan_device', to='inventory.Device', verbose_name='Device')),
                ('loaned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loaned_by', to=settings.AUTH_USER_MODEL, verbose_name='Loaned By')),
                ('loaned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loaned_to', to=settings.AUTH_USER_MODEL, verbose_name='Loaned To')),
            ],
            options={
                'verbose_name': 'Device Loan',
                'verbose_name_plural': 'Device Loans',
            },
        ),
        migrations.CreateModel(
            name='LoanRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Description')),
                ('created', models.DateTimeField(editable=False, verbose_name='Creation date and time')),
                ('modified', models.DateTimeField(editable=False, null=True, verbose_name='Modification date and time')),
                ('private', models.BooleanField(default=False, verbose_name='Private')),
                ('reason', models.TextField(max_length=1000, verbose_name='Reason')),
                ('status', models.CharField(choices=[('PE', 'Pending'), ('AP', 'Approved'), ('RE', 'Rejected'), ('HO', 'On Hold'), ('WI', 'Withdrawn')], default='PE', max_length=2, verbose_name='Status')),
                ('booked_from', models.TextField(max_length=100, verbose_name='Booked From')),
                ('booked_until', models.TextField(max_length=100, verbose_name='Booked Until')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_approved_by', to=settings.AUTH_USER_MODEL, verbose_name='Approved By')),
                ('case', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='loan_request_case', to='case.Case', verbose_name='Case')),
                ('device', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='loan_request_device', to='inventory.Device', verbose_name='Device')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_requested_by', to=settings.AUTH_USER_MODEL, verbose_name='Requested By')),
            ],
            options={
                'verbose_name': 'Loan Request',
                'verbose_name_plural': 'Loan Requests',
            },
        ),
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Description')),
                ('created', models.DateTimeField(editable=False, verbose_name='Creation date and time')),
                ('modified', models.DateTimeField(editable=False, null=True, verbose_name='Modification date and time')),
                ('private', models.BooleanField(default=False, verbose_name='Private')),
                ('reason', models.TextField(max_length=1000, verbose_name='Reason')),
                ('status', models.CharField(choices=[('PE', 'Pending'), ('AP', 'Approved'), ('RE', 'Rejected'), ('HO', 'On Hold'), ('WI', 'Withdrawn')], default='PE', max_length=2, verbose_name='Status')),
                ('actual_use', models.TextField(max_length=1000, verbose_name='Actual Use Time')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_approved_by', to=settings.AUTH_USER_MODEL, verbose_name='Approved By')),
                ('case', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='return_request_case', to='case.Case', verbose_name='Case')),
                ('device', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='return_request_device', to='inventory.Device', verbose_name='Device')),
                ('loan', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='device_loan', to='loan.Loan', verbose_name='Loan')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_requested_by', to=settings.AUTH_USER_MODEL, verbose_name='Requested By')),
            ],
            options={
                'verbose_name': 'Return Request',
                'verbose_name_plural': 'Return Requests',
            },
        ),
    ]
