# Generated by Django 2.0.3 on 2018-12-01 01:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('case', '0001_initial'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalLoan',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('private', models.BooleanField(default=False, verbose_name='Private')),
                ('description', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Description')),
                ('created', models.DateTimeField(editable=False, verbose_name='Creation date and time')),
                ('modified', models.DateTimeField(editable=False, null=True, verbose_name='Modification date and time')),
                ('reason', models.TextField(max_length=1000, verbose_name='Loan Reason')),
                ('approver_note', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Approver Note')),
                ('booked_from', models.TextField(max_length=100, verbose_name='Booked From')),
                ('booked_until', models.TextField(max_length=100, verbose_name='Booked Until')),
                ('original_condition', models.CharField(choices=[('NW', 'New'), ('EX', 'Excellent'), ('GD', 'Good'), ('AV', 'Average'), ('BA', 'Below Average'), ('PR', 'Poor'), ('DM', 'Damaged'), ('LO', 'Lost')], default='EX', max_length=2, verbose_name='Original Condition')),
                ('return_condition', models.CharField(choices=[('NW', 'New'), ('EX', 'Excellent'), ('GD', 'Good'), ('AV', 'Average'), ('BA', 'Below Average'), ('PR', 'Poor'), ('DM', 'Damaged'), ('LO', 'Lost')], default='EX', max_length=2, verbose_name='Returned Condition')),
                ('returned', models.BooleanField(default=False, verbose_name='Returned')),
                ('taken', models.BooleanField(default=False, verbose_name='Taken')),
                ('status', models.CharField(choices=[('LP', 'Loan Pending'), ('LA', 'Loan Approved'), ('LR', 'Loan Rejected'), ('LH', 'Loan On Hold'), ('LW', 'Loan Withdrawn'), ('RP', 'Return Pending'), ('RA', 'Return Approved'), ('RR', 'Return Rejected'), ('RH', 'Return On Hold'), ('RW', 'Return Withdrawn'), ('CL', 'Loan Closed')], default='LP', max_length=2, verbose_name='Status')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('case', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='case.Case')),
                ('device', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.Device')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('loaned_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('loaned_to', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Device Loan',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private', models.BooleanField(default=False, verbose_name='Private')),
                ('description', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Description')),
                ('created', models.DateTimeField(editable=False, verbose_name='Creation date and time')),
                ('modified', models.DateTimeField(editable=False, null=True, verbose_name='Modification date and time')),
                ('reason', models.TextField(max_length=1000, verbose_name='Loan Reason')),
                ('approver_note', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Approver Note')),
                ('booked_from', models.TextField(max_length=100, verbose_name='Booked From')),
                ('booked_until', models.TextField(max_length=100, verbose_name='Booked Until')),
                ('original_condition', models.CharField(choices=[('NW', 'New'), ('EX', 'Excellent'), ('GD', 'Good'), ('AV', 'Average'), ('BA', 'Below Average'), ('PR', 'Poor'), ('DM', 'Damaged'), ('LO', 'Lost')], default='EX', max_length=2, verbose_name='Original Condition')),
                ('return_condition', models.CharField(choices=[('NW', 'New'), ('EX', 'Excellent'), ('GD', 'Good'), ('AV', 'Average'), ('BA', 'Below Average'), ('PR', 'Poor'), ('DM', 'Damaged'), ('LO', 'Lost')], default='EX', max_length=2, verbose_name='Returned Condition')),
                ('returned', models.BooleanField(default=False, verbose_name='Returned')),
                ('taken', models.BooleanField(default=False, verbose_name='Taken')),
                ('status', models.CharField(choices=[('LP', 'Loan Pending'), ('LA', 'Loan Approved'), ('LR', 'Loan Rejected'), ('LH', 'Loan On Hold'), ('LW', 'Loan Withdrawn'), ('RP', 'Return Pending'), ('RA', 'Return Approved'), ('RR', 'Return Rejected'), ('RH', 'Return On Hold'), ('RW', 'Return Withdrawn'), ('CL', 'Loan Closed')], default='LP', max_length=2, verbose_name='Status')),
                ('case', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='loan_case', to='case.Case', verbose_name='Case')),
                ('device', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='loan_device', to='inventory.Device', verbose_name='Device')),
                ('loaned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loaned_by', to=settings.AUTH_USER_MODEL, verbose_name='Loaned By')),
                ('loaned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loaned_to', to=settings.AUTH_USER_MODEL, verbose_name='Loaned To')),
            ],
            options={
                'verbose_name': 'Device Loan',
                'verbose_name_plural': 'Device Loans',
            },
        ),
    ]
