# Generated by Django 2.0.3 on 2018-09-09 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalreturnrequest',
            name='device',
        ),
        migrations.RemoveField(
            model_name='returnrequest',
            name='device',
        ),
    ]
