# Generated by Django 2.0.3 on 2018-12-16 02:52

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loan', '0002_auto_20181208_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalloan',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='reason',
        ),
        migrations.AddField(
            model_name='historicalloan',
            name='date_returned',
            field=models.DateField(default=datetime.datetime(2018, 12, 16, 2, 51, 42, 691128, tzinfo=utc), help_text='Enter the date returned', verbose_name='Date Returned'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalloan',
            name='date_taken',
            field=models.DateField(default=datetime.datetime(2018, 12, 16, 2, 51, 46, 754148, tzinfo=utc), help_text='Enter the date taken', verbose_name='Date Taken'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalloan',
            name='return_note',
            field=models.TextField(blank=True, help_text='Enter a return note', max_length=1000, null=True, verbose_name='Return Note'),
        ),
        migrations.AddField(
            model_name='historicalloan',
            name='returned_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalloan',
            name='taken_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loan',
            name='date_returned',
            field=models.DateField(default=datetime.datetime(2018, 12, 16, 2, 51, 58, 237341, tzinfo=utc), help_text='Enter the date returned', verbose_name='Date Returned'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loan',
            name='date_taken',
            field=models.DateField(default=datetime.datetime(2018, 12, 16, 2, 52, 6, 682738, tzinfo=utc), help_text='Enter the date taken', verbose_name='Date Taken'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loan',
            name='return_note',
            field=models.TextField(blank=True, help_text='Enter a return note', max_length=1000, null=True, verbose_name='Return Note'),
        ),
        migrations.AddField(
            model_name='loan',
            name='returned_by',
            field=models.ForeignKey(blank=True, help_text='Select who the device was returned by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='returned_by', to=settings.AUTH_USER_MODEL, verbose_name='Returned By'),
        ),
        migrations.AddField(
            model_name='loan',
            name='taken_by',
            field=models.ForeignKey(blank=True, help_text='Select who the device was taken by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='taken_by', to=settings.AUTH_USER_MODEL, verbose_name='Taken By'),
        ),
        migrations.AlterField(
            model_name='historicalloan',
            name='approver_note',
            field=models.TextField(blank=True, help_text="Enter an approver's note", max_length=1000, null=True, verbose_name='Approver Note'),
        ),
        migrations.AlterField(
            model_name='historicalloan',
            name='booked_from',
            field=models.DateField(help_text='Enter the booked from date', verbose_name='Booked From'),
        ),
        migrations.AlterField(
            model_name='historicalloan',
            name='booked_until',
            field=models.DateField(help_text='Enter the booked until date', verbose_name='Booked Until'),
        ),
        migrations.AlterField(
            model_name='historicalloan',
            name='original_condition',
            field=models.CharField(choices=[('AV', 'Average'), ('BA', 'Below Average'), ('DM', 'Damaged'), ('EX', 'Excellent'), ('GD', 'Good'), ('LO', 'Lost'), ('MI', 'Missing'), ('NW', 'New'), ('PO', 'Poor')], help_text='Select the original condition', max_length=2, verbose_name='Original Condition'),
        ),
        migrations.AlterField(
            model_name='historicalloan',
            name='return_condition',
            field=models.CharField(choices=[('AV', 'Average'), ('BA', 'Below Average'), ('DM', 'Damaged'), ('EX', 'Excellent'), ('GD', 'Good'), ('LO', 'Lost'), ('MI', 'Missing'), ('NW', 'New'), ('PO', 'Poor')], help_text='Select the returned condition', max_length=2, verbose_name='Returned Condition'),
        ),
        migrations.AlterField(
            model_name='historicalloan',
            name='returned',
            field=models.BooleanField(default=False, help_text='Device returned', verbose_name='Returned'),
        ),
        migrations.AlterField(
            model_name='historicalloan',
            name='status',
            field=models.CharField(choices=[('LP', 'Awaiting Loan Approval'), ('LA', 'Loan Approved'), ('LR', 'Loan Rejected'), ('LH', 'Loan On Hold'), ('LW', 'Loan Withdrawn'), ('LC', 'Loan Closed'), ('RP', 'Awaiting Return Approval'), ('RA', 'Return Approved'), ('RR', 'Return Rejected'), ('RH', 'Return On Hold'), ('RW', 'Return Withdrawn')], help_text='Select the loan status', max_length=2, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='historicalloan',
            name='taken',
            field=models.BooleanField(default=False, help_text='Device taken', verbose_name='Taken'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='approver_note',
            field=models.TextField(blank=True, help_text="Enter an approver's note", max_length=1000, null=True, verbose_name='Approver Note'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='booked_from',
            field=models.DateField(help_text='Enter the booked from date', verbose_name='Booked From'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='booked_until',
            field=models.DateField(help_text='Enter the booked until date', verbose_name='Booked Until'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='case',
            field=models.ForeignKey(blank=True, help_text='Select the case', on_delete=django.db.models.deletion.DO_NOTHING, related_name='loan_case', to='case.Case', verbose_name='Case'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='device',
            field=models.ForeignKey(blank=True, help_text='Select the device', on_delete=django.db.models.deletion.DO_NOTHING, related_name='loan_device', to='inventory.Device', verbose_name='Device'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loaned_by',
            field=models.ForeignKey(blank=True, help_text='Select who the device is loaned by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='loaned_by', to=settings.AUTH_USER_MODEL, verbose_name='Loaned By'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loaned_to',
            field=models.ForeignKey(blank=True, help_text='Select who the device is loaned to', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='loaned_to', to=settings.AUTH_USER_MODEL, verbose_name='Loaned To'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='original_condition',
            field=models.CharField(choices=[('AV', 'Average'), ('BA', 'Below Average'), ('DM', 'Damaged'), ('EX', 'Excellent'), ('GD', 'Good'), ('LO', 'Lost'), ('MI', 'Missing'), ('NW', 'New'), ('PO', 'Poor')], help_text='Select the original condition', max_length=2, verbose_name='Original Condition'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='return_condition',
            field=models.CharField(choices=[('AV', 'Average'), ('BA', 'Below Average'), ('DM', 'Damaged'), ('EX', 'Excellent'), ('GD', 'Good'), ('LO', 'Lost'), ('MI', 'Missing'), ('NW', 'New'), ('PO', 'Poor')], help_text='Select the returned condition', max_length=2, verbose_name='Returned Condition'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='returned',
            field=models.BooleanField(default=False, help_text='Device returned', verbose_name='Returned'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('LP', 'Awaiting Loan Approval'), ('LA', 'Loan Approved'), ('LR', 'Loan Rejected'), ('LH', 'Loan On Hold'), ('LW', 'Loan Withdrawn'), ('LC', 'Loan Closed'), ('RP', 'Awaiting Return Approval'), ('RA', 'Return Approved'), ('RR', 'Return Rejected'), ('RH', 'Return On Hold'), ('RW', 'Return Withdrawn')], help_text='Select the loan status', max_length=2, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='taken',
            field=models.BooleanField(default=False, help_text='Device taken', verbose_name='Taken'),
        ),
    ]
