# Generated by Django 2.0.3 on 2018-09-09 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0002_auto_20180909_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalloan',
            name='taken',
            field=models.BooleanField(default=False, verbose_name='Taken'),
        ),
        migrations.AddField(
            model_name='loan',
            name='taken',
            field=models.BooleanField(default=False, verbose_name='Taken'),
        ),
        migrations.AlterField(
            model_name='historicalloan',
            name='status',
            field=models.CharField(choices=[('PE', 'Pending'), ('AP', 'Approved'), ('RE', 'Rejected'), ('HO', 'On Hold'), ('WI', 'Withdrawn'), ('RT', 'Returned')], default='PE', max_length=2, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='historicalloanrequest',
            name='status',
            field=models.CharField(choices=[('PE', 'Pending'), ('AP', 'Approved'), ('RE', 'Rejected'), ('HO', 'On Hold'), ('WI', 'Withdrawn'), ('RT', 'Returned')], default='PE', max_length=2, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='historicalreturnrequest',
            name='status',
            field=models.CharField(choices=[('PE', 'Pending'), ('AP', 'Approved'), ('RE', 'Rejected'), ('HO', 'On Hold'), ('WI', 'Withdrawn'), ('RT', 'Returned')], default='PE', max_length=2, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('PE', 'Pending'), ('AP', 'Approved'), ('RE', 'Rejected'), ('HO', 'On Hold'), ('WI', 'Withdrawn'), ('RT', 'Returned')], default='PE', max_length=2, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='status',
            field=models.CharField(choices=[('PE', 'Pending'), ('AP', 'Approved'), ('RE', 'Rejected'), ('HO', 'On Hold'), ('WI', 'Withdrawn'), ('RT', 'Returned')], default='PE', max_length=2, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='status',
            field=models.CharField(choices=[('PE', 'Pending'), ('AP', 'Approved'), ('RE', 'Rejected'), ('HO', 'On Hold'), ('WI', 'Withdrawn'), ('RT', 'Returned')], default='PE', max_length=2, verbose_name='Status'),
        ),
    ]
