# Generated by Django 2.0.3 on 2018-12-16 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0003_auto_20181216_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalloan',
            name='booked_from',
            field=models.DateField(blank=True, help_text='Enter the booked from date', null=True, verbose_name='Booked From'),
        ),
        migrations.AlterField(
            model_name='historicalloan',
            name='booked_until',
            field=models.DateField(blank=True, help_text='Enter the booked until date', null=True, verbose_name='Booked Until'),
        ),
        migrations.AlterField(
            model_name='historicalloan',
            name='date_returned',
            field=models.DateField(blank=True, help_text='Enter the date returned', null=True, verbose_name='Date Returned'),
        ),
        migrations.AlterField(
            model_name='historicalloan',
            name='date_taken',
            field=models.DateField(blank=True, help_text='Enter the date taken', null=True, verbose_name='Date Taken'),
        ),
        migrations.AlterField(
            model_name='historicalloan',
            name='original_condition',
            field=models.CharField(blank=True, choices=[('AV', 'Average'), ('BA', 'Below Average'), ('DM', 'Damaged'), ('EX', 'Excellent'), ('GD', 'Good'), ('LO', 'Lost'), ('MI', 'Missing'), ('NW', 'New'), ('PO', 'Poor')], help_text='Select the original condition', max_length=2, null=True, verbose_name='Original Condition'),
        ),
        migrations.AlterField(
            model_name='historicalloan',
            name='return_condition',
            field=models.CharField(blank=True, choices=[('AV', 'Average'), ('BA', 'Below Average'), ('DM', 'Damaged'), ('EX', 'Excellent'), ('GD', 'Good'), ('LO', 'Lost'), ('MI', 'Missing'), ('NW', 'New'), ('PO', 'Poor')], help_text='Select the returned condition', max_length=2, null=True, verbose_name='Returned Condition'),
        ),
        migrations.AlterField(
            model_name='historicalloan',
            name='status',
            field=models.CharField(blank=True, choices=[('LP', 'Awaiting Loan Approval'), ('LA', 'Loan Approved'), ('LR', 'Loan Rejected'), ('LH', 'Loan On Hold'), ('LW', 'Loan Withdrawn'), ('LC', 'Loan Closed'), ('RP', 'Awaiting Return Approval'), ('RA', 'Return Approved'), ('RR', 'Return Rejected'), ('RH', 'Return On Hold'), ('RW', 'Return Withdrawn')], help_text='Select the loan status', max_length=2, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='booked_from',
            field=models.DateField(blank=True, help_text='Enter the booked from date', null=True, verbose_name='Booked From'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='booked_until',
            field=models.DateField(blank=True, help_text='Enter the booked until date', null=True, verbose_name='Booked Until'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='date_returned',
            field=models.DateField(blank=True, help_text='Enter the date returned', null=True, verbose_name='Date Returned'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='date_taken',
            field=models.DateField(blank=True, help_text='Enter the date taken', null=True, verbose_name='Date Taken'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='original_condition',
            field=models.CharField(blank=True, choices=[('AV', 'Average'), ('BA', 'Below Average'), ('DM', 'Damaged'), ('EX', 'Excellent'), ('GD', 'Good'), ('LO', 'Lost'), ('MI', 'Missing'), ('NW', 'New'), ('PO', 'Poor')], help_text='Select the original condition', max_length=2, null=True, verbose_name='Original Condition'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='return_condition',
            field=models.CharField(blank=True, choices=[('AV', 'Average'), ('BA', 'Below Average'), ('DM', 'Damaged'), ('EX', 'Excellent'), ('GD', 'Good'), ('LO', 'Lost'), ('MI', 'Missing'), ('NW', 'New'), ('PO', 'Poor')], help_text='Select the returned condition', max_length=2, null=True, verbose_name='Returned Condition'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(blank=True, choices=[('LP', 'Awaiting Loan Approval'), ('LA', 'Loan Approved'), ('LR', 'Loan Rejected'), ('LH', 'Loan On Hold'), ('LW', 'Loan Withdrawn'), ('LC', 'Loan Closed'), ('RP', 'Awaiting Return Approval'), ('RA', 'Return Approved'), ('RR', 'Return Rejected'), ('RH', 'Return On Hold'), ('RW', 'Return Withdrawn')], help_text='Select the loan status', max_length=2, null=True, verbose_name='Status'),
        ),
    ]
