# Generated by Django 2.0.3 on 2018-09-09 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0004_auto_20180909_1206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalloan',
            name='condition',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='condition',
        ),
        migrations.AddField(
            model_name='historicalloan',
            name='original_condition',
            field=models.CharField(choices=[('NW', 'New'), ('EX', 'Excellent'), ('GD', 'Good'), ('AV', 'Average'), ('BA', 'Below Average'), ('PR', 'Poor'), ('DM', 'Damaged'), ('LO', 'Lost')], default='EX', max_length=2, verbose_name='Original Condition'),
        ),
        migrations.AddField(
            model_name='historicalloan',
            name='return_condition',
            field=models.CharField(choices=[('NW', 'New'), ('EX', 'Excellent'), ('GD', 'Good'), ('AV', 'Average'), ('BA', 'Below Average'), ('PR', 'Poor'), ('DM', 'Damaged'), ('LO', 'Lost')], default='EX', max_length=2, verbose_name='Returned Condition'),
        ),
        migrations.AddField(
            model_name='loan',
            name='original_condition',
            field=models.CharField(choices=[('NW', 'New'), ('EX', 'Excellent'), ('GD', 'Good'), ('AV', 'Average'), ('BA', 'Below Average'), ('PR', 'Poor'), ('DM', 'Damaged'), ('LO', 'Lost')], default='EX', max_length=2, verbose_name='Original Condition'),
        ),
        migrations.AddField(
            model_name='loan',
            name='return_condition',
            field=models.CharField(choices=[('NW', 'New'), ('EX', 'Excellent'), ('GD', 'Good'), ('AV', 'Average'), ('BA', 'Below Average'), ('PR', 'Poor'), ('DM', 'Damaged'), ('LO', 'Lost')], default='EX', max_length=2, verbose_name='Returned Condition'),
        ),
    ]
