# Generated by Django 2.0.3 on 2018-09-09 03:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0005_auto_20180909_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalloan',
            name='approver_note',
            field=models.TextField(default=django.utils.timezone.now, max_length=1000, verbose_name='Approver Note'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loan',
            name='approver_note',
            field=models.TextField(default=django.utils.timezone.now, max_length=1000, verbose_name='Approver Note'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicalloan',
            name='reason',
            field=models.TextField(max_length=1000, verbose_name='Loan Reason'),
        ),
        migrations.AlterField(
            model_name='historicalloan',
            name='status',
            field=models.CharField(choices=[('LP', 'Loan Pending'), ('LA', 'Loan Approved'), ('LR', 'Loan Rejected'), ('LH', 'Loan On Hold'), ('LW', 'Loan Withdrawn'), ('RP', 'Return Pending'), ('RA', 'Return Approved'), ('RR', 'Return Rejected'), ('RH', 'Return On Hold'), ('RW', 'Return Withdrawn'), ('CL', 'Loan Closed')], default='LP', max_length=2, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='reason',
            field=models.TextField(max_length=1000, verbose_name='Loan Reason'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('LP', 'Loan Pending'), ('LA', 'Loan Approved'), ('LR', 'Loan Rejected'), ('LH', 'Loan On Hold'), ('LW', 'Loan Withdrawn'), ('RP', 'Return Pending'), ('RA', 'Return Approved'), ('RR', 'Return Rejected'), ('RH', 'Return On Hold'), ('RW', 'Return Withdrawn'), ('CL', 'Loan Closed')], default='LP', max_length=2, verbose_name='Status'),
        ),
    ]
