# Generated by Django 2.0.3 on 2018-09-09 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0006_auto_20180909_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalloan',
            name='approver_note',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Approver Note'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='approver_note',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Approver Note'),
        ),
    ]
