# Generated by Django 2.0.3 on 2018-12-08 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0002_auto_20181208_1511'),
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventType',
        ),
        migrations.RemoveField(
            model_name='historicaleventtype',
            name='history_user',
        ),
        migrations.AlterField(
            model_name='eventcategory',
            name='colour',
            field=models.CharField(blank=True, default=None, help_text='(Optional) Enter a Hexidecimal colour representation', max_length=7, null=True, verbose_name='Colour'),
        ),
        migrations.AlterField(
            model_name='eventcategory',
            name='created',
            field=models.DateTimeField(editable=False, help_text='The creation date', verbose_name='Creation Date'),
        ),
        migrations.AlterField(
            model_name='eventcategory',
            name='description',
            field=models.CharField(blank=True, default=None, help_text='(Optional) Enter a description', max_length=250, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='eventcategory',
            name='modified',
            field=models.DateTimeField(editable=False, help_text='The mdification date', null=True, verbose_name='Modification date'),
        ),
        migrations.AlterField(
            model_name='eventcategory',
            name='title',
            field=models.CharField(default=None, help_text='Enter a title', max_length=50, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='eventclassification',
            name='colour',
            field=models.CharField(blank=True, default=None, help_text='(Optional) Enter a Hexidecimal colour representation', max_length=7, null=True, verbose_name='Colour'),
        ),
        migrations.AlterField(
            model_name='eventclassification',
            name='created',
            field=models.DateTimeField(editable=False, help_text='The creation date', verbose_name='Creation Date'),
        ),
        migrations.AlterField(
            model_name='eventclassification',
            name='description',
            field=models.CharField(blank=True, default=None, help_text='(Optional) Enter a description', max_length=250, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='eventclassification',
            name='modified',
            field=models.DateTimeField(editable=False, help_text='The mdification date', null=True, verbose_name='Modification date'),
        ),
        migrations.AlterField(
            model_name='eventclassification',
            name='title',
            field=models.CharField(default=None, help_text='Enter a title', max_length=50, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='eventpriority',
            name='colour',
            field=models.CharField(blank=True, default=None, help_text='(Optional) Enter a Hexidecimal colour representation', max_length=7, null=True, verbose_name='Colour'),
        ),
        migrations.AlterField(
            model_name='eventpriority',
            name='created',
            field=models.DateTimeField(editable=False, help_text='The creation date', verbose_name='Creation Date'),
        ),
        migrations.AlterField(
            model_name='eventpriority',
            name='description',
            field=models.CharField(blank=True, default=None, help_text='(Optional) Enter a description', max_length=250, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='eventpriority',
            name='modified',
            field=models.DateTimeField(editable=False, help_text='The mdification date', null=True, verbose_name='Modification date'),
        ),
        migrations.AlterField(
            model_name='eventpriority',
            name='title',
            field=models.CharField(default=None, help_text='Enter a title', max_length=50, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='eventstatus',
            name='colour',
            field=models.CharField(blank=True, default=None, help_text='(Optional) Enter a Hexidecimal colour representation', max_length=7, null=True, verbose_name='Colour'),
        ),
        migrations.AlterField(
            model_name='eventstatus',
            name='created',
            field=models.DateTimeField(editable=False, help_text='The creation date', verbose_name='Creation Date'),
        ),
        migrations.AlterField(
            model_name='eventstatus',
            name='description',
            field=models.CharField(blank=True, default=None, help_text='(Optional) Enter a description', max_length=250, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='eventstatus',
            name='modified',
            field=models.DateTimeField(editable=False, help_text='The mdification date', null=True, verbose_name='Modification date'),
        ),
        migrations.AlterField(
            model_name='eventstatus',
            name='title',
            field=models.CharField(default=None, help_text='Enter a title', max_length=50, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='eventstatusgroup',
            name='colour',
            field=models.CharField(blank=True, default=None, help_text='(Optional) Enter a Hexidecimal colour representation', max_length=7, null=True, verbose_name='Colour'),
        ),
        migrations.AlterField(
            model_name='eventstatusgroup',
            name='created',
            field=models.DateTimeField(editable=False, help_text='The creation date', verbose_name='Creation Date'),
        ),
        migrations.AlterField(
            model_name='eventstatusgroup',
            name='description',
            field=models.CharField(blank=True, default=None, help_text='(Optional) Enter a description', max_length=250, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='eventstatusgroup',
            name='modified',
            field=models.DateTimeField(editable=False, help_text='The mdification date', null=True, verbose_name='Modification date'),
        ),
        migrations.AlterField(
            model_name='eventstatusgroup',
            name='status',
            field=models.ManyToManyField(blank=True, help_text='Select Event Status', to='event.EventStatus', verbose_name='Event Status'),
        ),
        migrations.AlterField(
            model_name='eventstatusgroup',
            name='title',
            field=models.CharField(default=None, help_text='Enter a title', max_length=50, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='historicaleventcategory',
            name='colour',
            field=models.CharField(blank=True, default=None, help_text='(Optional) Enter a Hexidecimal colour representation', max_length=7, null=True, verbose_name='Colour'),
        ),
        migrations.AlterField(
            model_name='historicaleventcategory',
            name='created',
            field=models.DateTimeField(editable=False, help_text='The creation date', verbose_name='Creation Date'),
        ),
        migrations.AlterField(
            model_name='historicaleventcategory',
            name='description',
            field=models.CharField(blank=True, default=None, help_text='(Optional) Enter a description', max_length=250, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='historicaleventcategory',
            name='modified',
            field=models.DateTimeField(editable=False, help_text='The mdification date', null=True, verbose_name='Modification date'),
        ),
        migrations.AlterField(
            model_name='historicaleventcategory',
            name='title',
            field=models.CharField(default=None, help_text='Enter a title', max_length=50, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='historicaleventclassification',
            name='colour',
            field=models.CharField(blank=True, default=None, help_text='(Optional) Enter a Hexidecimal colour representation', max_length=7, null=True, verbose_name='Colour'),
        ),
        migrations.AlterField(
            model_name='historicaleventclassification',
            name='created',
            field=models.DateTimeField(editable=False, help_text='The creation date', verbose_name='Creation Date'),
        ),
        migrations.AlterField(
            model_name='historicaleventclassification',
            name='description',
            field=models.CharField(blank=True, default=None, help_text='(Optional) Enter a description', max_length=250, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='historicaleventclassification',
            name='modified',
            field=models.DateTimeField(editable=False, help_text='The mdification date', null=True, verbose_name='Modification date'),
        ),
        migrations.AlterField(
            model_name='historicaleventclassification',
            name='title',
            field=models.CharField(default=None, help_text='Enter a title', max_length=50, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='historicaleventpriority',
            name='colour',
            field=models.CharField(blank=True, default=None, help_text='(Optional) Enter a Hexidecimal colour representation', max_length=7, null=True, verbose_name='Colour'),
        ),
        migrations.AlterField(
            model_name='historicaleventpriority',
            name='created',
            field=models.DateTimeField(editable=False, help_text='The creation date', verbose_name='Creation Date'),
        ),
        migrations.AlterField(
            model_name='historicaleventpriority',
            name='description',
            field=models.CharField(blank=True, default=None, help_text='(Optional) Enter a description', max_length=250, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='historicaleventpriority',
            name='modified',
            field=models.DateTimeField(editable=False, help_text='The mdification date', null=True, verbose_name='Modification date'),
        ),
        migrations.AlterField(
            model_name='historicaleventpriority',
            name='title',
            field=models.CharField(default=None, help_text='Enter a title', max_length=50, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='historicaleventstatus',
            name='colour',
            field=models.CharField(blank=True, default=None, help_text='(Optional) Enter a Hexidecimal colour representation', max_length=7, null=True, verbose_name='Colour'),
        ),
        migrations.AlterField(
            model_name='historicaleventstatus',
            name='created',
            field=models.DateTimeField(editable=False, help_text='The creation date', verbose_name='Creation Date'),
        ),
        migrations.AlterField(
            model_name='historicaleventstatus',
            name='description',
            field=models.CharField(blank=True, default=None, help_text='(Optional) Enter a description', max_length=250, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='historicaleventstatus',
            name='modified',
            field=models.DateTimeField(editable=False, help_text='The mdification date', null=True, verbose_name='Modification date'),
        ),
        migrations.AlterField(
            model_name='historicaleventstatus',
            name='title',
            field=models.CharField(default=None, help_text='Enter a title', max_length=50, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='historicaleventstatusgroup',
            name='colour',
            field=models.CharField(blank=True, default=None, help_text='(Optional) Enter a Hexidecimal colour representation', max_length=7, null=True, verbose_name='Colour'),
        ),
        migrations.AlterField(
            model_name='historicaleventstatusgroup',
            name='created',
            field=models.DateTimeField(editable=False, help_text='The creation date', verbose_name='Creation Date'),
        ),
        migrations.AlterField(
            model_name='historicaleventstatusgroup',
            name='description',
            field=models.CharField(blank=True, default=None, help_text='(Optional) Enter a description', max_length=250, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='historicaleventstatusgroup',
            name='modified',
            field=models.DateTimeField(editable=False, help_text='The mdification date', null=True, verbose_name='Modification date'),
        ),
        migrations.AlterField(
            model_name='historicaleventstatusgroup',
            name='title',
            field=models.CharField(default=None, help_text='Enter a title', max_length=50, verbose_name='Title'),
        ),
        migrations.DeleteModel(
            name='HistoricalEventType',
        ),
    ]
