# Generated by Django 2.0.3 on 2018-12-08 05:11

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0002_auto_20181208_1511'),
        ('evidence', '0002_auto_20181208_1511'),
        ('case', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caseevent',
            name='brief',
        ),
        migrations.RemoveField(
            model_name='caseevent',
            name='type',
        ),
        migrations.RemoveField(
            model_name='caseevidence',
            name='brief',
        ),
        migrations.RemoveField(
            model_name='caseevidence',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='caseevidence',
            name='current_status',
        ),
        migrations.RemoveField(
            model_name='caseevidence',
            name='qr_code_text',
        ),
        migrations.RemoveField(
            model_name='caseevidence',
            name='retention_date',
        ),
        migrations.RemoveField(
            model_name='caseevidence',
            name='uri',
        ),
        migrations.RemoveField(
            model_name='casetask',
            name='background',
        ),
        migrations.RemoveField(
            model_name='casetask',
            name='brief',
        ),
        migrations.RemoveField(
            model_name='casetask',
            name='classification',
        ),
        migrations.RemoveField(
            model_name='casetask',
            name='type',
        ),
        migrations.RemoveField(
            model_name='historicalcaseevent',
            name='brief',
        ),
        migrations.RemoveField(
            model_name='historicalcaseevent',
            name='type',
        ),
        migrations.RemoveField(
            model_name='historicalcaseevidence',
            name='brief',
        ),
        migrations.RemoveField(
            model_name='historicalcaseevidence',
            name='chain_of_custody',
        ),
        migrations.RemoveField(
            model_name='historicalcaseevidence',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='historicalcaseevidence',
            name='current_status',
        ),
        migrations.RemoveField(
            model_name='historicalcaseevidence',
            name='qr_code_text',
        ),
        migrations.RemoveField(
            model_name='historicalcaseevidence',
            name='retention_date',
        ),
        migrations.RemoveField(
            model_name='historicalcaseevidence',
            name='uri',
        ),
        migrations.RemoveField(
            model_name='historicalcasetask',
            name='background',
        ),
        migrations.RemoveField(
            model_name='historicalcasetask',
            name='brief',
        ),
        migrations.RemoveField(
            model_name='historicalcasetask',
            name='classification',
        ),
        migrations.RemoveField(
            model_name='historicalcasetask',
            name='type',
        ),
        migrations.AddField(
            model_name='caseevent',
            name='note',
            field=models.ManyToManyField(blank=True, help_text='(Optional) Enter a note relating to the Event', related_name='Event_note', to='utils.Note', verbose_name='Note'),
        ),
        migrations.AddField(
            model_name='caseevidence',
            name='file_location',
            field=models.FileField(blank=True, help_text='Upload a file location for the Evidence', null=True, upload_to='', verbose_name='File Location'),
        ),
        migrations.AddField(
            model_name='caseevidence',
            name='image_upload',
            field=models.FileField(blank=True, help_text='Upload an image for the Evidence', null=True, upload_to='', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='caseevidence',
            name='note',
            field=models.ManyToManyField(blank=True, help_text='(Optional) Enter a note relating to the Evidence', null=True, related_name='evidence_note', to='utils.Note', verbose_name='Note'),
        ),
        migrations.AddField(
            model_name='caseevidence',
            name='retention_end_date',
            field=models.DateTimeField(blank=True, help_text='Enter the retention end date', null=True, verbose_name='Retention End Date'),
        ),
        migrations.AddField(
            model_name='casetask',
            name='note',
            field=models.ManyToManyField(blank=True, help_text='(Optional) Enter a note relating to the Task', related_name='task_note', to='utils.Note', verbose_name='Note'),
        ),
        migrations.AddField(
            model_name='historicalcaseevidence',
            name='file_location',
            field=models.TextField(blank=True, help_text='Upload a file location for the Evidence', max_length=100, null=True, verbose_name='File Location'),
        ),
        migrations.AddField(
            model_name='historicalcaseevidence',
            name='image_upload',
            field=models.TextField(blank=True, help_text='Upload an image for the Evidence', max_length=100, null=True, verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='historicalcaseevidence',
            name='retention_end_date',
            field=models.DateTimeField(blank=True, help_text='Enter the retention end date', null=True, verbose_name='Retention End Date'),
        ),
        migrations.AlterField(
            model_name='case',
            name='created',
            field=models.DateTimeField(editable=False, help_text='The creation date', verbose_name='Creation Date'),
        ),
        migrations.AlterField(
            model_name='case',
            name='description',
            field=models.CharField(blank=True, default=None, help_text='(Optional) Enter a description', max_length=250, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='case',
            name='modified',
            field=models.DateTimeField(editable=False, help_text='The mdification date', null=True, verbose_name='Modification date'),
        ),
        migrations.AlterField(
            model_name='case',
            name='private',
            field=models.BooleanField(default=False, help_text='(Optional) Is Private', verbose_name='Private'),
        ),
        migrations.AlterField(
            model_name='casecategory',
            name='colour',
            field=models.CharField(blank=True, default=None, help_text='(Optional) Enter a Hexidecimal colour representation', max_length=7, null=True, verbose_name='Colour'),
        ),
        migrations.AlterField(
            model_name='casecategory',
            name='created',
            field=models.DateTimeField(editable=False, help_text='The creation date', verbose_name='Creation Date'),
        ),
        migrations.AlterField(
            model_name='casecategory',
            name='description',
            field=models.CharField(blank=True, default=None, help_text='(Optional) Enter a description', max_length=250, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='casecategory',
            name='modified',
            field=models.DateTimeField(editable=False, help_text='The mdification date', null=True, verbose_name='Modification date'),
        ),
        migrations.AlterField(
            model_name='casecategory',
            name='title',
            field=models.CharField(default=None, help_text='Enter a title', max_length=50, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='caseclassification',
            name='colour',
            field=models.CharField(blank=True, default=None, help_text='(Optional) Enter a Hexidecimal colour representation', max_length=7, null=True, verbose_name='Colour'),
        ),
        migrations.AlterField(
            model_name='caseclassification',
            name='created',
            field=models.DateTimeField(editable=False, help_text='The creation date', verbose_name='Creation Date'),
        ),
        migrations.AlterField(
            model_name='caseclassification',
            name='description',
            field=models.CharField(blank=True, default=None, help_text='(Optional) Enter a description', max_length=250, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='caseclassification',
            name='modified',
            field=models.DateTimeField(editable=False, help_text='The mdification date', null=True, verbose_name='Modification date'),
        ),
        migrations.AlterField(
            model_name='caseclassification',
            name='title',
            field=models.CharField(default=None, help_text='Enter a title', max_length=50, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='casecompany',
            name='created',
            field=models.DateTimeField(editable=False, help_text='The creation date', verbose_name='Creation Date'),
        ),
        migrations.AlterField(
            model_name='casecompany',
            name='description',
            field=models.CharField(blank=True, default=None, help_text='(Optional) Enter a description', max_length=250, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='casecompany',
            name='modified',
            field=models.DateTimeField(editable=False, help_text='The mdification date', null=True, verbose_name='Modification date'),
        ),
        migrations.AlterField(
            model_name='casecompany',
            name='private',
            field=models.BooleanField(default=False, help_text='(Optional) Is Private', verbose_name='Private'),
        ),
        migrations.AlterField(
            model_name='caseevent',
            name='assigned_by',
            field=models.ForeignKey(blank=True, help_text='(Optional) Select Event assigned by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Event_assigned_by', to=settings.AUTH_USER_MODEL, verbose_name='Assigned By'),
        ),
        migrations.AlterField(
            model_name='caseevent',
            name='assigned_to',
            field=models.ManyToManyField(blank=True, help_text='(Optional) Select Event assigned to', related_name='Event_assigned_to', to=settings.AUTH_USER_MODEL, verbose_name='Assigned To'),
        ),
        migrations.AlterField(
            model_name='caseevent',
            name='authorisation',
            field=models.ForeignKey(blank=True, help_text='(Optional) Select the authorisation of the Event', null=True, on_delete=django.db.models.deletion.SET_NULL, to='utils.Authorisation', verbose_name='Authorisation'),
        ),
        migrations.AlterField(
            model_name='caseevent',
            name='category',
            field=models.ForeignKey(blank=True, help_text='(Optional) Select the category of Event', null=True, on_delete=django.db.models.deletion.SET_NULL, to='event.EventCategory', verbose_name='Event Category'),
        ),
        migrations.AlterField(
            model_name='caseevent',
            name='classification',
            field=models.ForeignKey(blank=True, help_text='(Optional) Select the classification of Event', null=True, on_delete=django.db.models.deletion.SET_NULL, to='event.EventClassification', verbose_name='Event Classification'),
        ),
        migrations.AlterField(
            model_name='caseevent',
            name='created',
            field=models.DateTimeField(editable=False, help_text='The creation date', verbose_name='Creation Date'),
        ),
        migrations.AlterField(
            model_name='caseevent',
            name='description',
            field=models.CharField(blank=True, default=None, help_text='(Optional) Enter a description', max_length=250, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='caseevent',
            name='image_upload',
            field=models.FileField(blank=True, help_text='Upload an image for the Task', null=True, upload_to='', verbose_name='Event Image'),
        ),
        migrations.AlterField(
            model_name='caseevent',
            name='manager',
            field=models.ForeignKey(blank=True, help_text='(Optional) Select the Event Manager', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Event_manager', to=settings.AUTH_USER_MODEL, verbose_name='Event Manager'),
        ),
        migrations.AlterField(
            model_name='caseevent',
            name='modified',
            field=models.DateTimeField(editable=False, help_text='The mdification date', null=True, verbose_name='Modification date'),
        ),
        migrations.AlterField(
            model_name='caseevent',
            name='priority',
            field=models.ForeignKey(blank=True, help_text='(Optional) Select the priority of the Event', null=True, on_delete=django.db.models.deletion.SET_NULL, to='event.EventPriority', verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='caseevent',
            name='private',
            field=models.BooleanField(default=False, help_text='(Optional) Is Private', verbose_name='Private'),
        ),
        migrations.AlterField(
            model_name='caseevent',
            name='slug',
            field=models.SlugField(blank=True, help_text='A slug value representing title', null=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='caseevent',
            name='status',
            field=models.ForeignKey(blank=True, help_text='(Optional) Select the status of the Event', null=True, on_delete=django.db.models.deletion.SET_NULL, to='event.EventStatus', verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='caseevent',
            name='title',
            field=models.CharField(default=None, help_text='Enter a title for the Task', max_length=128, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='caseevidence',
            name='assigned_by',
            field=models.ForeignKey(blank=True, help_text='(Optional) Select Evidence assigned by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidence_assigned_by', to=settings.AUTH_USER_MODEL, verbose_name='Assigned By'),
        ),
        migrations.AlterField(
            model_name='caseevidence',
            name='assigned_to',
            field=models.ManyToManyField(blank=True, help_text='(Optional) Select Evidence assigned to', related_name='evidence_assigned_to', to=settings.AUTH_USER_MODEL, verbose_name='Assigned To'),
        ),
        migrations.AlterField(
            model_name='caseevidence',
            name='authorisation',
            field=models.ForeignKey(blank=True, help_text='(Optional) Select the authorisation of the Evidence', null=True, on_delete=django.db.models.deletion.SET_NULL, to='utils.Authorisation', verbose_name='Authorisation'),
        ),
        migrations.AlterField(
            model_name='caseevidence',
            name='bag_number',
            field=models.CharField(blank=True, default=None, help_text='Enter a bag number for the Evidence', max_length=50, null=True, verbose_name='Bag Number'),
        ),
        migrations.AlterField(
            model_name='caseevidence',
            name='category',
            field=models.ForeignKey(blank=True, help_text='(Optional) Select the category of Evidence', null=True, on_delete=django.db.models.deletion.SET_NULL, to='evidence.EvidenceCategory', verbose_name='Evidence Category'),
        ),
        migrations.RemoveField(
            model_name='caseevidence',
            name='chain_of_custody',
        ),
        migrations.AddField(
            model_name='caseevidence',
            name='chain_of_custody',
            field=models.ManyToManyField(blank=True, help_text='(Optional) Enter the chain of custody', null=True, to='evidence.ChainOfCustody', verbose_name='Chain Of Custody'),
        ),
        migrations.AlterField(
            model_name='caseevidence',
            name='classification',
            field=models.ForeignKey(blank=True, help_text='(Optional) Select the classification of Evidence', null=True, on_delete=django.db.models.deletion.SET_NULL, to='evidence.EvidenceClassification', verbose_name='Evidence Classification'),
        ),
        migrations.AlterField(
            model_name='caseevidence',
            name='created',
            field=models.DateTimeField(editable=False, help_text='The creation date', verbose_name='Creation Date'),
        ),
        migrations.AlterField(
            model_name='caseevidence',
            name='custodian',
            field=models.ForeignKey(blank=True, help_text='(Optional) Select the Evidence Custodian', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidence_custodian', to=settings.AUTH_USER_MODEL, verbose_name='Evidence Custodian'),
        ),
        migrations.AlterField(
            model_name='caseevidence',
            name='description',
            field=models.CharField(blank=True, default=None, help_text='(Optional) Enter a description', max_length=250, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='caseevidence',
            name='location',
            field=models.CharField(blank=True, default=None, help_text='Enter a current location for the Evidence', max_length=250, null=True, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='caseevidence',
            name='modified',
            field=models.DateTimeField(editable=False, help_text='The mdification date', null=True, verbose_name='Modification date'),
        ),
        migrations.AlterField(
            model_name='caseevidence',
            name='priority',
            field=models.ForeignKey(blank=True, help_text='(Optional) Select the priority of the Evidence', null=True, on_delete=django.db.models.deletion.SET_NULL, to='evidence.EvidencePriority', verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='caseevidence',
            name='private',
            field=models.BooleanField(default=False, help_text='(Optional) Is Private', verbose_name='Private'),
        ),
        migrations.AlterField(
            model_name='caseevidence',
            name='qr_code',
            field=models.CharField(blank=True, default=None, help_text='Enter a QR code for the evidence', max_length=128, null=True, verbose_name='QR Code'),
        ),
        migrations.AlterField(
            model_name='caseevidence',
            name='reference',
            field=models.CharField(blank=True, default=None, help_text='Enter a reference code for the Evidence', max_length=50, null=True, verbose_name='Reference'),
        ),
        migrations.AlterField(
            model_name='caseevidence',
            name='retention_reminder_sent',
            field=models.BooleanField(default=False, help_text='Has a rentention reminder been sent', verbose_name='Retention Reminder'),
        ),
        migrations.AlterField(
            model_name='caseevidence',
            name='retention_start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 12, 8, 5, 11, 16, 359860, tzinfo=utc), help_text='Enter the retention start date', null=True, verbose_name='Retention Start Date'),
        ),
        migrations.AlterField(
            model_name='caseevidence',
            name='slug',
            field=models.SlugField(blank=True, help_text='A slug value representing title', null=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='caseevidence',
            name='status',
            field=models.ForeignKey(blank=True, help_text='(Optional) Select the status of the Evidence', null=True, on_delete=django.db.models.deletion.SET_NULL, to='evidence.EvidenceStatus', verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='caseevidence',
            name='title',
            field=models.CharField(default=None, help_text='Enter a title for the Evidence', max_length=128, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='caseevidence',
            name='type',
            field=models.ForeignKey(blank=True, help_text='(Optional) Select the type of Evidence', null=True, on_delete=django.db.models.deletion.SET_NULL, to='evidence.EvidenceType', verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='caseinventory',
            name='created',
            field=models.DateTimeField(editable=False, help_text='The creation date', verbose_name='Creation Date'),
        ),
        migrations.AlterField(
            model_name='caseinventory',
            name='description',
            field=models.CharField(blank=True, default=None, help_text='(Optional) Enter a description', max_length=250, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='caseinventory',
            name='modified',
            field=models.DateTimeField(editable=False, help_text='The mdification date', null=True, verbose_name='Modification date'),
        ),
        migrations.AlterField(
            model_name='caseinventory',
            name='private',
            field=models.BooleanField(default=False, help_text='(Optional) Is Private', verbose_name='Private'),
        ),
        migrations.AlterField(
            model_name='caseperson',
            name='created',
            field=models.DateTimeField(editable=False, help_text='The creation date', verbose_name='Creation Date'),
        ),
        migrations.AlterField(
            model_name='caseperson',
            name='description',
            field=models.CharField(blank=True, default=None, help_text='(Optional) Enter a description', max_length=250, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='caseperson',
            name='modified',
            field=models.DateTimeField(editable=False, help_text='The mdification date', null=True, verbose_name='Modification date'),
        ),
        migrations.AlterField(
            model_name='caseperson',
            name='private',
            field=models.BooleanField(default=False, help_text='(Optional) Is Private', verbose_name='Private'),
        ),
        migrations.AlterField(
            model_name='casepriority',
            name='colour',
            field=models.CharField(blank=True, default=None, help_text='(Optional) Enter a Hexidecimal colour representation', max_length=7, null=True, verbose_name='Colour'),
        ),
        migrations.AlterField(
            model_name='casepriority',
            name='created',
            field=models.DateTimeField(editable=False, help_text='The creation date', verbose_name='Creation Date'),
        ),
        migrations.AlterField(
            model_name='casepriority',
            name='description',
            field=models.CharField(blank=True, default=None, help_text='(Optional) Enter a description', max_length=250, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='casepriority',
            name='modified',
            field=models.DateTimeField(editable=False, help_text='The mdification date', null=True, verbose_name='Modification date'),
        ),
        migrations.AlterField(
            model_name='casepriority',
            name='title',
            field=models.CharField(default=None, help_text='Enter a title', max_length=50, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='casestatus',
            name='colour',
            field=models.CharField(blank=True, default=None, help_text='(Optional) Enter a Hexidecimal colour representation', max_length=7, null=True, verbose_name='Colour'),
        ),
        migrations.AlterField(
            model_name='casestatus',
            name='created',
            field=models.DateTimeField(editable=False, help_text='The creation date', verbose_name='Creation Date'),
        ),
        migrations.AlterField(
            model_name='casestatus',
            name='description',
            field=models.CharField(blank=True, default=None, help_text='(Optional) Enter a description', max_length=250, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='casestatus',
            name='modified',
            field=models.DateTimeField(editable=False, help_text='The mdification date', null=True, verbose_name='Modification date'),
        ),
        migrations.AlterField(
            model_name='casestatus',
            name='title',
            field=models.CharField(default=None, help_text='Enter a title', max_length=50, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='casestatusgroup',
            name='colour',
            field=models.CharField(blank=True, default=None, help_text='(Optional) Enter a Hexidecimal colour representation', max_length=7, null=True, verbose_name='Colour'),
        ),
        migrations.AlterField(
            model_name='casestatusgroup',
            name='created',
            field=models.DateTimeField(editable=False, help_text='The creation date', verbose_name='Creation Date'),
        ),
        migrations.AlterField(
            model_name='casestatusgroup',
            name='description',
            field=models.CharField(blank=True, default=None, help_text='(Optional) Enter a description', max_length=250, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='casestatusgroup',
            name='modified',
            field=models.DateTimeField(editable=False, help_text='The mdification date', null=True, verbose_name='Modification date'),
        ),
        migrations.AlterField(
            model_name='casestatusgroup',
            name='title',
            field=models.CharField(default=None, help_text='Enter a title', max_length=50, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='casetask',
            name='assigned_by',
            field=models.ForeignKey(blank=True, help_text='(Optional) Select Task assigned by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_assigned_by', to=settings.AUTH_USER_MODEL, verbose_name='Assigned By'),
        ),
        migrations.AlterField(
            model_name='casetask',
            name='assigned_to',
            field=models.ManyToManyField(blank=True, help_text='(Optional) Select Task assigned to', related_name='task_assigned_to', to=settings.AUTH_USER_MODEL, verbose_name='Assigned To'),
        ),
        migrations.AlterField(
            model_name='casetask',
            name='authorisation',
            field=models.ForeignKey(blank=True, help_text='(Optional) Select the authorisation of the Task', null=True, on_delete=django.db.models.deletion.SET_NULL, to='utils.Authorisation', verbose_name='Authorisation'),
        ),
        migrations.AlterField(
            model_name='casetask',
            name='category',
            field=models.ForeignKey(blank=True, help_text='(Optional) Select the category of Task', null=True, on_delete=django.db.models.deletion.SET_NULL, to='task.TaskCategory', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='casetask',
            name='created',
            field=models.DateTimeField(editable=False, help_text='The creation date', verbose_name='Creation Date'),
        ),
        migrations.AlterField(
            model_name='casetask',
            name='description',
            field=models.CharField(blank=True, default=None, help_text='(Optional) Enter a description', max_length=250, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='casetask',
            name='location',
            field=models.CharField(blank=True, default=None, help_text='(Optional) Enter a location for the task', max_length=250, null=True, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='casetask',
            name='manager',
            field=models.ForeignKey(blank=True, help_text='(Optional) Select the Task Manager', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_manager', to=settings.AUTH_USER_MODEL, verbose_name='Task Manager'),
        ),
        migrations.AlterField(
            model_name='casetask',
            name='modified',
            field=models.DateTimeField(editable=False, help_text='The mdification date', null=True, verbose_name='Modification date'),
        ),
        migrations.AlterField(
            model_name='casetask',
            name='priority',
            field=models.ForeignKey(blank=True, help_text='(Optional) Select the priority of the Task', null=True, on_delete=django.db.models.deletion.SET_NULL, to='task.TaskPriority', verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='casetask',
            name='private',
            field=models.BooleanField(default=False, help_text='(Optional) Is Private', verbose_name='Private'),
        ),
        migrations.AlterField(
            model_name='casetask',
            name='slug',
            field=models.SlugField(blank=True, help_text='A slug value representing title', null=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='casetask',
            name='status',
            field=models.ForeignKey(blank=True, help_text='(Optional) Select the status of the Task', null=True, on_delete=django.db.models.deletion.SET_NULL, to='task.TaskStatus', verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='casetask',
            name='title',
            field=models.CharField(default=None, help_text='Enter a title for the Task', max_length=128, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='casetype',
            name='colour',
            field=models.CharField(blank=True, default=None, help_text='(Optional) Enter a Hexidecimal colour representation', max_length=7, null=True, verbose_name='Colour'),
        ),
        migrations.AlterField(
            model_name='casetype',
            name='created',
            field=models.DateTimeField(editable=False, help_text='The creation date', verbose_name='Creation Date'),
        ),
        migrations.AlterField(
            model_name='casetype',
            name='description',
            field=models.CharField(blank=True, default=None, help_text='(Optional) Enter a description', max_length=250, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='casetype',
            name='modified',
            field=models.DateTimeField(editable=False, help_text='The mdification date', null=True, verbose_name='Modification date'),
        ),
        migrations.AlterField(
            model_name='casetype',
            name='title',
            field=models.CharField(default=None, help_text='Enter a title', max_length=50, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='historicalcase',
            name='created',
            field=models.DateTimeField(editable=False, help_text='The creation date', verbose_name='Creation Date'),
        ),
        migrations.AlterField(
            model_name='historicalcase',
            name='description',
            field=models.CharField(blank=True, default=None, help_text='(Optional) Enter a description', max_length=250, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='historicalcase',
            name='modified',
            field=models.DateTimeField(editable=False, help_text='The mdification date', null=True, verbose_name='Modification date'),
        ),
        migrations.AlterField(
            model_name='historicalcase',
            name='private',
            field=models.BooleanField(default=False, help_text='(Optional) Is Private', verbose_name='Private'),
        ),
        migrations.AlterField(
            model_name='historicalcasecategory',
            name='colour',
            field=models.CharField(blank=True, default=None, help_text='(Optional) Enter a Hexidecimal colour representation', max_length=7, null=True, verbose_name='Colour'),
        ),
        migrations.AlterField(
            model_name='historicalcasecategory',
            name='created',
            field=models.DateTimeField(editable=False, help_text='The creation date', verbose_name='Creation Date'),
        ),
        migrations.AlterField(
            model_name='historicalcasecategory',
            name='description',
            field=models.CharField(blank=True, default=None, help_text='(Optional) Enter a description', max_length=250, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='historicalcasecategory',
            name='modified',
            field=models.DateTimeField(editable=False, help_text='The mdification date', null=True, verbose_name='Modification date'),
        ),
        migrations.AlterField(
            model_name='historicalcasecategory',
            name='title',
            field=models.CharField(default=None, help_text='Enter a title', max_length=50, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='historicalcaseclassification',
            name='colour',
            field=models.CharField(blank=True, default=None, help_text='(Optional) Enter a Hexidecimal colour representation', max_length=7, null=True, verbose_name='Colour'),
        ),
        migrations.AlterField(
            model_name='historicalcaseclassification',
            name='created',
            field=models.DateTimeField(editable=False, help_text='The creation date', verbose_name='Creation Date'),
        ),
        migrations.AlterField(
            model_name='historicalcaseclassification',
            name='description',
            field=models.CharField(blank=True, default=None, help_text='(Optional) Enter a description', max_length=250, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='historicalcaseclassification',
            name='modified',
            field=models.DateTimeField(editable=False, help_text='The mdification date', null=True, verbose_name='Modification date'),
        ),
        migrations.AlterField(
            model_name='historicalcaseclassification',
            name='title',
            field=models.CharField(default=None, help_text='Enter a title', max_length=50, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='historicalcasecompany',
            name='created',
            field=models.DateTimeField(editable=False, help_text='The creation date', verbose_name='Creation Date'),
        ),
        migrations.AlterField(
            model_name='historicalcasecompany',
            name='description',
            field=models.CharField(blank=True, default=None, help_text='(Optional) Enter a description', max_length=250, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='historicalcasecompany',
            name='modified',
            field=models.DateTimeField(editable=False, help_text='The mdification date', null=True, verbose_name='Modification date'),
        ),
        migrations.AlterField(
            model_name='historicalcasecompany',
            name='private',
            field=models.BooleanField(default=False, help_text='(Optional) Is Private', verbose_name='Private'),
        ),
        migrations.AlterField(
            model_name='historicalcaseevent',
            name='created',
            field=models.DateTimeField(editable=False, help_text='The creation date', verbose_name='Creation Date'),
        ),
        migrations.AlterField(
            model_name='historicalcaseevent',
            name='description',
            field=models.CharField(blank=True, default=None, help_text='(Optional) Enter a description', max_length=250, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='historicalcaseevent',
            name='image_upload',
            field=models.TextField(blank=True, help_text='Upload an image for the Task', max_length=100, null=True, verbose_name='Event Image'),
        ),
        migrations.AlterField(
            model_name='historicalcaseevent',
            name='modified',
            field=models.DateTimeField(editable=False, help_text='The mdification date', null=True, verbose_name='Modification date'),
        ),
        migrations.AlterField(
            model_name='historicalcaseevent',
            name='private',
            field=models.BooleanField(default=False, help_text='(Optional) Is Private', verbose_name='Private'),
        ),
        migrations.AlterField(
            model_name='historicalcaseevent',
            name='slug',
            field=models.SlugField(blank=True, help_text='A slug value representing title', null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='historicalcaseevent',
            name='title',
            field=models.CharField(default=None, help_text='Enter a title for the Task', max_length=128, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='historicalcaseevidence',
            name='bag_number',
            field=models.CharField(blank=True, default=None, help_text='Enter a bag number for the Evidence', max_length=50, null=True, verbose_name='Bag Number'),
        ),
        migrations.AlterField(
            model_name='historicalcaseevidence',
            name='created',
            field=models.DateTimeField(editable=False, help_text='The creation date', verbose_name='Creation Date'),
        ),
        migrations.AlterField(
            model_name='historicalcaseevidence',
            name='description',
            field=models.CharField(blank=True, default=None, help_text='(Optional) Enter a description', max_length=250, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='historicalcaseevidence',
            name='location',
            field=models.CharField(blank=True, default=None, help_text='Enter a current location for the Evidence', max_length=250, null=True, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='historicalcaseevidence',
            name='modified',
            field=models.DateTimeField(editable=False, help_text='The mdification date', null=True, verbose_name='Modification date'),
        ),
        migrations.AlterField(
            model_name='historicalcaseevidence',
            name='private',
            field=models.BooleanField(default=False, help_text='(Optional) Is Private', verbose_name='Private'),
        ),
        migrations.AlterField(
            model_name='historicalcaseevidence',
            name='qr_code',
            field=models.CharField(blank=True, default=None, help_text='Enter a QR code for the evidence', max_length=128, null=True, verbose_name='QR Code'),
        ),
        migrations.AlterField(
            model_name='historicalcaseevidence',
            name='reference',
            field=models.CharField(blank=True, default=None, help_text='Enter a reference code for the Evidence', max_length=50, null=True, verbose_name='Reference'),
        ),
        migrations.AlterField(
            model_name='historicalcaseevidence',
            name='retention_reminder_sent',
            field=models.BooleanField(default=False, help_text='Has a rentention reminder been sent', verbose_name='Retention Reminder'),
        ),
        migrations.AlterField(
            model_name='historicalcaseevidence',
            name='retention_start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 12, 8, 5, 11, 16, 359860, tzinfo=utc), help_text='Enter the retention start date', null=True, verbose_name='Retention Start Date'),
        ),
        migrations.AlterField(
            model_name='historicalcaseevidence',
            name='slug',
            field=models.SlugField(blank=True, help_text='A slug value representing title', null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='historicalcaseevidence',
            name='title',
            field=models.CharField(default=None, help_text='Enter a title for the Evidence', max_length=128, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='historicalcaseinventory',
            name='created',
            field=models.DateTimeField(editable=False, help_text='The creation date', verbose_name='Creation Date'),
        ),
        migrations.AlterField(
            model_name='historicalcaseinventory',
            name='description',
            field=models.CharField(blank=True, default=None, help_text='(Optional) Enter a description', max_length=250, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='historicalcaseinventory',
            name='modified',
            field=models.DateTimeField(editable=False, help_text='The mdification date', null=True, verbose_name='Modification date'),
        ),
        migrations.AlterField(
            model_name='historicalcaseinventory',
            name='private',
            field=models.BooleanField(default=False, help_text='(Optional) Is Private', verbose_name='Private'),
        ),
        migrations.AlterField(
            model_name='historicalcaseperson',
            name='created',
            field=models.DateTimeField(editable=False, help_text='The creation date', verbose_name='Creation Date'),
        ),
        migrations.AlterField(
            model_name='historicalcaseperson',
            name='description',
            field=models.CharField(blank=True, default=None, help_text='(Optional) Enter a description', max_length=250, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='historicalcaseperson',
            name='modified',
            field=models.DateTimeField(editable=False, help_text='The mdification date', null=True, verbose_name='Modification date'),
        ),
        migrations.AlterField(
            model_name='historicalcaseperson',
            name='private',
            field=models.BooleanField(default=False, help_text='(Optional) Is Private', verbose_name='Private'),
        ),
        migrations.AlterField(
            model_name='historicalcasepriority',
            name='colour',
            field=models.CharField(blank=True, default=None, help_text='(Optional) Enter a Hexidecimal colour representation', max_length=7, null=True, verbose_name='Colour'),
        ),
        migrations.AlterField(
            model_name='historicalcasepriority',
            name='created',
            field=models.DateTimeField(editable=False, help_text='The creation date', verbose_name='Creation Date'),
        ),
        migrations.AlterField(
            model_name='historicalcasepriority',
            name='description',
            field=models.CharField(blank=True, default=None, help_text='(Optional) Enter a description', max_length=250, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='historicalcasepriority',
            name='modified',
            field=models.DateTimeField(editable=False, help_text='The mdification date', null=True, verbose_name='Modification date'),
        ),
        migrations.AlterField(
            model_name='historicalcasepriority',
            name='title',
            field=models.CharField(default=None, help_text='Enter a title', max_length=50, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='historicalcasestatus',
            name='colour',
            field=models.CharField(blank=True, default=None, help_text='(Optional) Enter a Hexidecimal colour representation', max_length=7, null=True, verbose_name='Colour'),
        ),
        migrations.AlterField(
            model_name='historicalcasestatus',
            name='created',
            field=models.DateTimeField(editable=False, help_text='The creation date', verbose_name='Creation Date'),
        ),
        migrations.AlterField(
            model_name='historicalcasestatus',
            name='description',
            field=models.CharField(blank=True, default=None, help_text='(Optional) Enter a description', max_length=250, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='historicalcasestatus',
            name='modified',
            field=models.DateTimeField(editable=False, help_text='The mdification date', null=True, verbose_name='Modification date'),
        ),
        migrations.AlterField(
            model_name='historicalcasestatus',
            name='title',
            field=models.CharField(default=None, help_text='Enter a title', max_length=50, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='historicalcasestatusgroup',
            name='colour',
            field=models.CharField(blank=True, default=None, help_text='(Optional) Enter a Hexidecimal colour representation', max_length=7, null=True, verbose_name='Colour'),
        ),
        migrations.AlterField(
            model_name='historicalcasestatusgroup',
            name='created',
            field=models.DateTimeField(editable=False, help_text='The creation date', verbose_name='Creation Date'),
        ),
        migrations.AlterField(
            model_name='historicalcasestatusgroup',
            name='description',
            field=models.CharField(blank=True, default=None, help_text='(Optional) Enter a description', max_length=250, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='historicalcasestatusgroup',
            name='modified',
            field=models.DateTimeField(editable=False, help_text='The mdification date', null=True, verbose_name='Modification date'),
        ),
        migrations.AlterField(
            model_name='historicalcasestatusgroup',
            name='title',
            field=models.CharField(default=None, help_text='Enter a title', max_length=50, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='historicalcasetask',
            name='created',
            field=models.DateTimeField(editable=False, help_text='The creation date', verbose_name='Creation Date'),
        ),
        migrations.AlterField(
            model_name='historicalcasetask',
            name='description',
            field=models.CharField(blank=True, default=None, help_text='(Optional) Enter a description', max_length=250, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='historicalcasetask',
            name='location',
            field=models.CharField(blank=True, default=None, help_text='(Optional) Enter a location for the task', max_length=250, null=True, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='historicalcasetask',
            name='modified',
            field=models.DateTimeField(editable=False, help_text='The mdification date', null=True, verbose_name='Modification date'),
        ),
        migrations.AlterField(
            model_name='historicalcasetask',
            name='private',
            field=models.BooleanField(default=False, help_text='(Optional) Is Private', verbose_name='Private'),
        ),
        migrations.AlterField(
            model_name='historicalcasetask',
            name='slug',
            field=models.SlugField(blank=True, help_text='A slug value representing title', null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='historicalcasetask',
            name='title',
            field=models.CharField(default=None, help_text='Enter a title for the Task', max_length=128, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='historicalcasetype',
            name='colour',
            field=models.CharField(blank=True, default=None, help_text='(Optional) Enter a Hexidecimal colour representation', max_length=7, null=True, verbose_name='Colour'),
        ),
        migrations.AlterField(
            model_name='historicalcasetype',
            name='created',
            field=models.DateTimeField(editable=False, help_text='The creation date', verbose_name='Creation Date'),
        ),
        migrations.AlterField(
            model_name='historicalcasetype',
            name='description',
            field=models.CharField(blank=True, default=None, help_text='(Optional) Enter a description', max_length=250, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='historicalcasetype',
            name='modified',
            field=models.DateTimeField(editable=False, help_text='The mdification date', null=True, verbose_name='Modification date'),
        ),
        migrations.AlterField(
            model_name='historicalcasetype',
            name='title',
            field=models.CharField(default=None, help_text='Enter a title', max_length=50, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='historicallinkedcase',
            name='created',
            field=models.DateTimeField(editable=False, help_text='The creation date', verbose_name='Creation Date'),
        ),
        migrations.AlterField(
            model_name='historicallinkedcase',
            name='description',
            field=models.CharField(blank=True, default=None, help_text='(Optional) Enter a description', max_length=250, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='historicallinkedcase',
            name='modified',
            field=models.DateTimeField(editable=False, help_text='The mdification date', null=True, verbose_name='Modification date'),
        ),
        migrations.AlterField(
            model_name='historicallinkedcase',
            name='private',
            field=models.BooleanField(default=False, help_text='(Optional) Is Private', verbose_name='Private'),
        ),
        migrations.AlterField(
            model_name='linkedcase',
            name='created',
            field=models.DateTimeField(editable=False, help_text='The creation date', verbose_name='Creation Date'),
        ),
        migrations.AlterField(
            model_name='linkedcase',
            name='description',
            field=models.CharField(blank=True, default=None, help_text='(Optional) Enter a description', max_length=250, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='linkedcase',
            name='modified',
            field=models.DateTimeField(editable=False, help_text='The mdification date', null=True, verbose_name='Modification date'),
        ),
        migrations.AlterField(
            model_name='linkedcase',
            name='private',
            field=models.BooleanField(default=False, help_text='(Optional) Is Private', verbose_name='Private'),
        ),
    ]
