# Generated by Django 2.0.3 on 2019-04-22 02:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseevent',
            name='company',
            field=models.ManyToManyField(blank=True, help_text='Select Companies', related_name='case_event_company', to='entity.Company', verbose_name='Companies Involved'),
        ),
        migrations.AlterField(
            model_name='caseevent',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 22, 2, 17, 14, 284832, tzinfo=utc), help_text='Select a date for the Task', verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='caseevent',
            name='evidence',
            field=models.ManyToManyField(blank=True, help_text='Select Evidence', related_name='case_event_evidence', to='case.CaseEvidence', verbose_name='Evidence Involved'),
        ),
        migrations.AlterField(
            model_name='caseevent',
            name='person',
            field=models.ManyToManyField(blank=True, help_text='Select Persons', related_name='case_event_person', to='entity.Person', verbose_name='Persons'),
        ),
        migrations.AlterField(
            model_name='casetask',
            name='company',
            field=models.ManyToManyField(blank=True, help_text='Select Companies', related_name='case_task_company', to='entity.Company', verbose_name='Companies Involved'),
        ),
        migrations.AlterField(
            model_name='casetask',
            name='device',
            field=models.ManyToManyField(blank=True, help_text='Select Evidence', related_name='case_task_device', to='case.CaseInventory', verbose_name='Devices Involved'),
        ),
        migrations.AlterField(
            model_name='casetask',
            name='event',
            field=models.ManyToManyField(blank=True, help_text='Select Events', related_name='case_task_event', to='case.CaseEvent', verbose_name='Events Involved'),
        ),
        migrations.AlterField(
            model_name='casetask',
            name='evidence',
            field=models.ManyToManyField(blank=True, help_text='Select Evidence', related_name='case_task_evidence', to='case.CaseEvidence', verbose_name='Evidence Involved'),
        ),
        migrations.AlterField(
            model_name='casetask',
            name='person',
            field=models.ManyToManyField(blank=True, help_text='Select Persons', related_name='case_task_person', to='entity.Person', verbose_name='Persons Involved'),
        ),
        migrations.AlterField(
            model_name='historicalcaseevent',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 22, 2, 17, 14, 284832, tzinfo=utc), help_text='Select a date for the Task', verbose_name='Date'),
        ),
    ]
