# Generated by Django 2.0.3 on 2018-07-08 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casenote',
            name='assigned_by',
        ),
        migrations.RemoveField(
            model_name='casenote',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='casenote',
            name='authorisation',
        ),
        migrations.RemoveField(
            model_name='casenote',
            name='case',
        ),
        migrations.RemoveField(
            model_name='casenote',
            name='category',
        ),
        migrations.RemoveField(
            model_name='casenote',
            name='classification',
        ),
        migrations.RemoveField(
            model_name='casenote',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='casenote',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='casenote',
            name='status',
        ),
        migrations.RemoveField(
            model_name='casenote',
            name='type',
        ),
        migrations.DeleteModel(
            name='CaseNote',
        ),
    ]
