# Generated by Django 2.0.3 on 2018-07-26 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='case',
            options={'verbose_name': 'Case', 'verbose_name_plural': 'Cases'},
        ),
    ]
