# Generated by Django 2.0.3 on 2018-07-22 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0002_auto_20180722_1046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='historicalcase',
            name='date_added',
        ),
        migrations.AlterField(
            model_name='case',
            name='deadline',
            field=models.DateTimeField(null=True, verbose_name='Deadline'),
        ),
        migrations.AlterField(
            model_name='historicalcase',
            name='deadline',
            field=models.DateTimeField(null=True, verbose_name='Deadline'),
        ),
    ]
