# Generated by Django 2.0.3 on 2018-07-27 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0002_auto_20180726_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalcase',
            name='assigned_by',
        ),
        migrations.RemoveField(
            model_name='historicalcase',
            name='authorisation',
        ),
        migrations.RemoveField(
            model_name='historicalcase',
            name='category',
        ),
        migrations.RemoveField(
            model_name='historicalcase',
            name='classification',
        ),
        migrations.RemoveField(
            model_name='historicalcase',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalcase',
            name='managed_by',
        ),
        migrations.RemoveField(
            model_name='historicalcase',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='historicalcase',
            name='status',
        ),
        migrations.RemoveField(
            model_name='historicalcase',
            name='type',
        ),
        migrations.AlterField(
            model_name='caseevidence',
            name='retention_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Retention Date'),
        ),
        migrations.AlterField(
            model_name='historicalcaseevidence',
            name='retention_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Retention Date'),
        ),
        migrations.DeleteModel(
            name='HistoricalCase',
        ),
    ]
