# Generated by Django 2.0.3 on 2019-04-22 03:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0002_auto_20190422_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseevent',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 22, 3, 3, 6, 708550, tzinfo=utc), help_text='Select a date for the Task', verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='historicalcaseevent',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 22, 3, 3, 6, 708550, tzinfo=utc), help_text='Select a date for the Task', verbose_name='Date'),
        ),
    ]
