# Generated by Django 2.0.3 on 2018-12-08 05:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0002_auto_20181208_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseevidence',
            name='chain_of_custody',
            field=models.ManyToManyField(blank=True, help_text='(Optional) Enter the chain of custody', to='evidence.ChainOfCustody', verbose_name='Chain Of Custody'),
        ),
        migrations.AlterField(
            model_name='caseevidence',
            name='retention_start_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='Enter the retention start date', null=True, verbose_name='Retention Start Date'),
        ),
        migrations.AlterField(
            model_name='historicalcaseevidence',
            name='retention_start_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='Enter the retention start date', null=True, verbose_name='Retention Start Date'),
        ),
    ]
