# Generated by Django 2.0.3 on 2018-07-27 08:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0018_auto_20180727_1815'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('case', '0004_historicalcase_historicalcaseauthorisation_historicalcasecategory_historicalcaseclassification_histo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Description')),
                ('created', models.DateTimeField(editable=False, verbose_name='Creation date and time')),
                ('modified', models.DateTimeField(editable=False, null=True, verbose_name='Modification date and time')),
                ('private', models.BooleanField(default=False, verbose_name='Private')),
                ('reason', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Reason For Link')),
                ('case', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='entity_linked_case', to='case.Case', verbose_name='Case')),
                ('linked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entity_linked_by', to=settings.AUTH_USER_MODEL, verbose_name='Linked By')),
                ('person', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='entity.Person', verbose_name='Case')),
            ],
            options={
                'verbose_name': 'Case Entity',
                'verbose_name_plural': 'Case Entities',
            },
        ),
        migrations.CreateModel(
            name='HistoricalCaseEntity',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('description', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Description')),
                ('created', models.DateTimeField(editable=False, verbose_name='Creation date and time')),
                ('modified', models.DateTimeField(editable=False, null=True, verbose_name='Modification date and time')),
                ('private', models.BooleanField(default=False, verbose_name='Private')),
                ('reason', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Reason For Link')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('case', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='case.Case')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('linked_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('person', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='entity.Person')),
            ],
            options={
                'verbose_name': 'historical Case Entity',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
        ),
        migrations.AlterField(
            model_name='linkedcase',
            name='case',
            field=models.ManyToManyField(blank=True, related_name='case_linked_case', to='case.Case', verbose_name='Case'),
        ),
        migrations.AlterField(
            model_name='linkedcase',
            name='linked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_linked_by', to=settings.AUTH_USER_MODEL, verbose_name='Linked By'),
        ),
    ]
