# Generated by Django 2.0.3 on 2019-04-28 02:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0004_auto_20190422_1303'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caseevent',
            options={'permissions': (('set_caseevent_manager', 'Set Event Manager'), ('set_caseevent_private', 'Set Event Private')), 'verbose_name': 'Case Event', 'verbose_name_plural': 'Case Event'},
        ),
        migrations.AlterModelOptions(
            name='caseevidence',
            options={'permissions': (('set_caseevidence_private', 'Set Evidence Private'),), 'verbose_name': 'Case Evidence', 'verbose_name_plural': 'Case Evidence'},
        ),
        migrations.AlterField(
            model_name='caseevent',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 28, 2, 33, 58, 509395, tzinfo=utc), help_text='Select a date for the Task', verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='historicalcaseevent',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 28, 2, 33, 58, 509395, tzinfo=utc), help_text='Select a date for the Task', verbose_name='Date'),
        ),
    ]
