# Generated by Django 2.0.3 on 2018-07-22 04:30

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0004_auto_20180722_1413'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='case',
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
