# Generated by Django 2.0.3 on 2018-07-22 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0005_auto_20180722_1430'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='case',
            managers=[
            ],
        ),
    ]
