# Generated by Django 2.0.3 on 2018-07-28 01:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entity', '0019_auto_20180728_1136'),
        ('case', '0005_auto_20180727_1815'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Description')),
                ('created', models.DateTimeField(editable=False, verbose_name='Creation date and time')),
                ('modified', models.DateTimeField(editable=False, null=True, verbose_name='Modification date and time')),
                ('private', models.BooleanField(default=False, verbose_name='Private')),
                ('role', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Role')),
                ('notes', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Notes')),
                ('type', models.CharField(choices=[('RL', 'Related'), ('UR', 'Unrelated'), ('UN', 'Unknown'), ('SU', 'Suspect'), ('IN', 'Informant'), ('AQ', 'Acquaintance'), ('VI', 'Victim'), ('WK', 'Working'), ('AS', 'Assisting')], default='UN', max_length=2, verbose_name='Type')),
                ('case', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='company_linked_case', to='case.Case', verbose_name='Case')),
                ('company', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='entity.Person', verbose_name='Case')),
                ('linked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_linked_by', to=settings.AUTH_USER_MODEL, verbose_name='Linked By')),
            ],
            options={
                'verbose_name': 'Case Entity',
                'verbose_name_plural': 'Case Entities',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CasePerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Description')),
                ('created', models.DateTimeField(editable=False, verbose_name='Creation date and time')),
                ('modified', models.DateTimeField(editable=False, null=True, verbose_name='Modification date and time')),
                ('private', models.BooleanField(default=False, verbose_name='Private')),
                ('role', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Role')),
                ('notes', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Notes')),
                ('type', models.CharField(choices=[('RL', 'Related'), ('UR', 'Unrelated'), ('UN', 'Unknown'), ('SU', 'Suspect'), ('IN', 'Informant'), ('AQ', 'Acquaintance'), ('VI', 'Victim'), ('WK', 'Working'), ('AS', 'Assisting')], default='UN', max_length=2, verbose_name='Type')),
                ('case', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='person_linked_case', to='case.Case', verbose_name='Case')),
                ('linked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person_linked_by', to=settings.AUTH_USER_MODEL, verbose_name='Linked By')),
                ('person', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='entity.Person', verbose_name='Case')),
            ],
            options={
                'verbose_name': 'Case Entity',
                'verbose_name_plural': 'Case Entities',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricalCaseCompany',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('description', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Description')),
                ('created', models.DateTimeField(editable=False, verbose_name='Creation date and time')),
                ('modified', models.DateTimeField(editable=False, null=True, verbose_name='Modification date and time')),
                ('private', models.BooleanField(default=False, verbose_name='Private')),
                ('role', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Role')),
                ('notes', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Notes')),
                ('type', models.CharField(choices=[('RL', 'Related'), ('UR', 'Unrelated'), ('UN', 'Unknown'), ('SU', 'Suspect'), ('IN', 'Informant'), ('AQ', 'Acquaintance'), ('VI', 'Victim'), ('WK', 'Working'), ('AS', 'Assisting')], default='UN', max_length=2, verbose_name='Type')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('case', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='case.Case')),
                ('company', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='entity.Person')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('linked_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Case Entity',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
        ),
        migrations.CreateModel(
            name='HistoricalCasePerson',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('description', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Description')),
                ('created', models.DateTimeField(editable=False, verbose_name='Creation date and time')),
                ('modified', models.DateTimeField(editable=False, null=True, verbose_name='Modification date and time')),
                ('private', models.BooleanField(default=False, verbose_name='Private')),
                ('role', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Role')),
                ('notes', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Notes')),
                ('type', models.CharField(choices=[('RL', 'Related'), ('UR', 'Unrelated'), ('UN', 'Unknown'), ('SU', 'Suspect'), ('IN', 'Informant'), ('AQ', 'Acquaintance'), ('VI', 'Victim'), ('WK', 'Working'), ('AS', 'Assisting')], default='UN', max_length=2, verbose_name='Type')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('case', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='case.Case')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('linked_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('person', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='entity.Person')),
            ],
            options={
                'verbose_name': 'historical Case Entity',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
        ),
        migrations.RemoveField(
            model_name='caseentity',
            name='case',
        ),
        migrations.RemoveField(
            model_name='caseentity',
            name='linked_by',
        ),
        migrations.RemoveField(
            model_name='caseentity',
            name='person',
        ),
        migrations.RemoveField(
            model_name='historicalcaseentity',
            name='case',
        ),
        migrations.RemoveField(
            model_name='historicalcaseentity',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalcaseentity',
            name='linked_by',
        ),
        migrations.RemoveField(
            model_name='historicalcaseentity',
            name='person',
        ),
        migrations.DeleteModel(
            name='CaseEntity',
        ),
        migrations.DeleteModel(
            name='HistoricalCaseEntity',
        ),
    ]
