# Generated by Django 2.0.3 on 2018-12-08 23:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0002_auto_20181208_1511'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('case', '0005_auto_20181208_1958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicallinkedcase',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicallinkedcase',
            name='linked_by',
        ),
        migrations.RemoveField(
            model_name='linkedcase',
            name='case',
        ),
        migrations.RemoveField(
            model_name='linkedcase',
            name='linked_by',
        ),
        migrations.RenameField(
            model_name='historicalcase',
            old_name='managed_by',
            new_name='manager',
        ),
        migrations.RemoveField(
            model_name='case',
            name='brief',
        ),
        migrations.RemoveField(
            model_name='case',
            name='location',
        ),
        migrations.RemoveField(
            model_name='case',
            name='managed_by',
        ),
        migrations.RemoveField(
            model_name='casecompany',
            name='linked_by',
        ),
        migrations.RemoveField(
            model_name='caseinventory',
            name='linked_by',
        ),
        migrations.RemoveField(
            model_name='caseinventory',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='caseinventory',
            name='returned',
        ),
        migrations.RemoveField(
            model_name='caseinventory',
            name='status',
        ),
        migrations.RemoveField(
            model_name='caseperson',
            name='linked_by',
        ),
        migrations.RemoveField(
            model_name='casetask',
            name='inventory',
        ),
        migrations.RemoveField(
            model_name='historicalcase',
            name='brief',
        ),
        migrations.RemoveField(
            model_name='historicalcase',
            name='location',
        ),
        migrations.RemoveField(
            model_name='historicalcasecompany',
            name='linked_by',
        ),
        migrations.RemoveField(
            model_name='historicalcaseinventory',
            name='linked_by',
        ),
        migrations.RemoveField(
            model_name='historicalcaseinventory',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='historicalcaseinventory',
            name='returned',
        ),
        migrations.RemoveField(
            model_name='historicalcaseinventory',
            name='status',
        ),
        migrations.RemoveField(
            model_name='historicalcaseperson',
            name='linked_by',
        ),
        migrations.AddField(
            model_name='case',
            name='manager',
            field=models.ForeignKey(blank=True, help_text='Select a case manager', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case_manager', to=settings.AUTH_USER_MODEL, verbose_name='Case Manager'),
        ),
        migrations.AddField(
            model_name='caseinventory',
            name='active',
            field=models.BooleanField(default=True, help_text='Is the case device Active', verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='caseinventory',
            name='note',
            field=models.ManyToManyField(help_text='Enter a case inventory Note', related_name='case_inventory_note', to='utils.Note', verbose_name='Case Inventory Note'),
        ),
        migrations.AddField(
            model_name='casetask',
            name='device',
            field=models.ManyToManyField(help_text='Select Evidence', related_name='case_task_device', to='case.CaseInventory', verbose_name='Devices Involved'),
        ),
        migrations.AddField(
            model_name='historicalcaseinventory',
            name='active',
            field=models.BooleanField(default=True, help_text='Is the case device Active', verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='case',
            name='assigned_by',
            field=models.ForeignKey(blank=True, help_text='Select assigned by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case_assigned_by', to=settings.AUTH_USER_MODEL, verbose_name='Assigned By'),
        ),
        migrations.AlterField(
            model_name='case',
            name='assigned_to',
            field=models.ManyToManyField(help_text='Select assigned to', related_name='case_assigned_to', to=settings.AUTH_USER_MODEL, verbose_name='Assigned To'),
        ),
        migrations.AlterField(
            model_name='case',
            name='authorisation',
            field=models.ForeignKey(blank=True, help_text='Select a case authorisation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_authorisation', to='utils.Authorisation', verbose_name='Case Authorisation'),
        ),
        migrations.AlterField(
            model_name='case',
            name='background',
            field=models.TextField(blank=True, help_text='Enter a background for the Case', null=True, verbose_name='Case Background'),
        ),
        migrations.AlterField(
            model_name='case',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Select a case category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_category', to='case.CaseCategory', verbose_name='Case Category'),
        ),
        migrations.AlterField(
            model_name='case',
            name='classification',
            field=models.ForeignKey(blank=True, help_text='Select a case classification', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_classification', to='case.CaseClassification', verbose_name='Case Classification'),
        ),
        migrations.AlterField(
            model_name='case',
            name='description',
            field=models.TextField(blank=True, help_text='Enter a description for the Case', null=True, verbose_name='Case Description'),
        ),
        migrations.AlterField(
            model_name='case',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='case',
            name='image_upload',
            field=models.FileField(blank=True, help_text='Upload an image for the Case', null=True, upload_to='', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='case',
            name='priority',
            field=models.ForeignKey(blank=True, help_text='Select a case priority', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_priority', to='case.CasePriority', verbose_name='Case Priority'),
        ),
        migrations.AlterField(
            model_name='case',
            name='purpose',
            field=models.CharField(blank=True, help_text='Enter a purpose for the Case', max_length=2500, null=True, verbose_name='Case Purpose'),
        ),
        migrations.AlterField(
            model_name='case',
            name='reference',
            field=models.CharField(blank=True, help_text='Enter a reference code for the Case', max_length=45, null=True, verbose_name='Reference'),
        ),
        migrations.AlterField(
            model_name='case',
            name='slug',
            field=models.SlugField(blank=True, help_text='A slug value representing title', null=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.ForeignKey(blank=True, help_text='Select a case status', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_status', to='case.CaseStatus', verbose_name='Case Status'),
        ),
        migrations.AlterField(
            model_name='case',
            name='title',
            field=models.CharField(default='Title', help_text='Enter a title for the Case', max_length=350, verbose_name='Title'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='case',
            name='type',
            field=models.ForeignKey(blank=True, help_text='Select a case type', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_type', to='case.CaseType', verbose_name='Case Type'),
        ),
        migrations.AlterField(
            model_name='casecompany',
            name='case',
            field=models.ForeignKey(help_text='(Optional) Select Case', on_delete=django.db.models.deletion.DO_NOTHING, related_name='case_company_case', to='case.Case', verbose_name='Case'),
        ),
        migrations.AlterField(
            model_name='casecompany',
            name='company',
            field=models.ForeignKey(help_text='Select Company', on_delete=django.db.models.deletion.DO_NOTHING, related_name='case_company_company', to='entity.Company', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='casecompany',
            name='role',
            field=models.CharField(blank=True, help_text='(Optional) Role of Entity', max_length=500, null=True, verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='casecompany',
            name='type',
            field=models.CharField(choices=[('ACQ', 'Acquaintance'), ('AST', 'Assisting'), ('CLI', 'Client'), ('DEF', 'Defendant'), ('INF', 'Informant'), ('PLA', 'Plaintiff'), ('RLT', 'Related'), ('SUS', 'Suspect'), ('UNR', 'Unrelated'), ('UNK', 'Unknown'), ('VIC', 'Victim'), ('WIT', 'Witness')], help_text='(Optional) Type of Entity', max_length=3, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='caseevent',
            name='case',
            field=models.ForeignKey(default=1, help_text='Select a Case', on_delete=django.db.models.deletion.CASCADE, related_name='case_event_case', to='case.Case', verbose_name='Case'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='caseevent',
            name='company',
            field=models.ManyToManyField(help_text='Select Companies', related_name='case_event_company', to='entity.Company', verbose_name='Companies Involved'),
        ),
        migrations.AlterField(
            model_name='caseevent',
            name='evidence',
            field=models.ManyToManyField(help_text='Select Evidence', related_name='case_event_evidence', to='case.CaseEvidence', verbose_name='Evidence Involved'),
        ),
        migrations.AlterField(
            model_name='caseevent',
            name='note',
            field=models.ManyToManyField(blank=True, help_text='(Optional) Enter a note relating to the Event', related_name='event_note', to='utils.Note', verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='caseevent',
            name='person',
            field=models.ManyToManyField(help_text='Select Persons', related_name='case_event_person', to='entity.Person', verbose_name='Persons'),
        ),
        migrations.AlterField(
            model_name='caseevidence',
            name='case',
            field=models.ForeignKey(default=1, help_text='Select Case', on_delete=django.db.models.deletion.DO_NOTHING, to='case.Case', verbose_name='Case'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='caseevidence',
            name='reference',
            field=models.CharField(blank=True, default=None, help_text='Enter a reference code for the Evidence', max_length=45, null=True, verbose_name='Reference'),
        ),
        migrations.AlterField(
            model_name='caseinventory',
            name='case',
            field=models.ForeignKey(default=1, help_text='Select a Case', on_delete=django.db.models.deletion.CASCADE, related_name='case_inventory_case', to='case.Case', verbose_name='Case'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='caseinventory',
            name='device',
            field=models.ForeignKey(help_text='Select a Device', on_delete=django.db.models.deletion.DO_NOTHING, related_name='case_inventory_device', to='inventory.Device', verbose_name='Device'),
        ),
        migrations.AlterField(
            model_name='caseperson',
            name='case',
            field=models.ForeignKey(help_text='Select Case', on_delete=django.db.models.deletion.DO_NOTHING, related_name='case_person_case', to='case.Case', verbose_name='Case'),
        ),
        migrations.AlterField(
            model_name='caseperson',
            name='person',
            field=models.ForeignKey(help_text='Select Person', on_delete=django.db.models.deletion.DO_NOTHING, related_name='case_person_person', to='entity.Person', verbose_name='Person'),
        ),
        migrations.AlterField(
            model_name='caseperson',
            name='role',
            field=models.CharField(blank=True, help_text='(Optional) Role of Entity', max_length=500, null=True, verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='caseperson',
            name='type',
            field=models.CharField(choices=[('ACQ', 'Acquaintance'), ('AST', 'Assisting'), ('CLI', 'Client'), ('DEF', 'Defendant'), ('INF', 'Informant'), ('PLA', 'Plaintiff'), ('RLT', 'Related'), ('SUS', 'Suspect'), ('UNR', 'Unrelated'), ('UNK', 'Unknown'), ('VIC', 'Victim'), ('WIT', 'Witness')], help_text='(Optional) Type of Entity', max_length=3, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='casestatusgroup',
            name='status',
            field=models.ManyToManyField(blank=True, help_text='Select Case Status', to='case.CaseStatus', verbose_name='Case Status'),
        ),
        migrations.AlterField(
            model_name='casetask',
            name='case',
            field=models.ForeignKey(default=1, help_text='Select a Case', on_delete=django.db.models.deletion.CASCADE, related_name='case_task_case', to='case.Case', verbose_name='Case'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='casetask',
            name='company',
            field=models.ManyToManyField(help_text='Select Companies', related_name='case_task_company', to='entity.Company', verbose_name='Companies Involved'),
        ),
        migrations.AlterField(
            model_name='casetask',
            name='event',
            field=models.ManyToManyField(help_text='Select Events', related_name='case_task_event', to='case.CaseEvent', verbose_name='Events Involved'),
        ),
        migrations.AlterField(
            model_name='casetask',
            name='evidence',
            field=models.ManyToManyField(help_text='Select Evidence', related_name='case_task_evidence', to='case.CaseEvidence', verbose_name='Evidence Involved'),
        ),
        migrations.AlterField(
            model_name='casetask',
            name='person',
            field=models.ManyToManyField(help_text='Select Persons', related_name='case_task_person', to='entity.Person', verbose_name='Persons Involved'),
        ),
        migrations.AlterField(
            model_name='historicalcase',
            name='background',
            field=models.TextField(blank=True, help_text='Enter a background for the Case', null=True, verbose_name='Case Background'),
        ),
        migrations.AlterField(
            model_name='historicalcase',
            name='description',
            field=models.TextField(blank=True, help_text='Enter a description for the Case', null=True, verbose_name='Case Description'),
        ),
        migrations.AlterField(
            model_name='historicalcase',
            name='id',
            field=models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='historicalcase',
            name='image_upload',
            field=models.TextField(blank=True, help_text='Upload an image for the Case', max_length=100, null=True, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='historicalcase',
            name='purpose',
            field=models.CharField(blank=True, help_text='Enter a purpose for the Case', max_length=2500, null=True, verbose_name='Case Purpose'),
        ),
        migrations.AlterField(
            model_name='historicalcase',
            name='reference',
            field=models.CharField(blank=True, help_text='Enter a reference code for the Case', max_length=45, null=True, verbose_name='Reference'),
        ),
        migrations.AlterField(
            model_name='historicalcase',
            name='slug',
            field=models.SlugField(blank=True, help_text='A slug value representing title', null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='historicalcase',
            name='title',
            field=models.CharField(default='Title', help_text='Enter a title for the Case', max_length=350, verbose_name='Title'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicalcasecompany',
            name='role',
            field=models.CharField(blank=True, help_text='(Optional) Role of Entity', max_length=500, null=True, verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='historicalcasecompany',
            name='type',
            field=models.CharField(choices=[('ACQ', 'Acquaintance'), ('AST', 'Assisting'), ('CLI', 'Client'), ('DEF', 'Defendant'), ('INF', 'Informant'), ('PLA', 'Plaintiff'), ('RLT', 'Related'), ('SUS', 'Suspect'), ('UNR', 'Unrelated'), ('UNK', 'Unknown'), ('VIC', 'Victim'), ('WIT', 'Witness')], help_text='(Optional) Type of Entity', max_length=3, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='historicalcaseevidence',
            name='reference',
            field=models.CharField(blank=True, default=None, help_text='Enter a reference code for the Evidence', max_length=45, null=True, verbose_name='Reference'),
        ),
        migrations.AlterField(
            model_name='historicalcaseperson',
            name='role',
            field=models.CharField(blank=True, help_text='(Optional) Role of Entity', max_length=500, null=True, verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='historicalcaseperson',
            name='type',
            field=models.CharField(choices=[('ACQ', 'Acquaintance'), ('AST', 'Assisting'), ('CLI', 'Client'), ('DEF', 'Defendant'), ('INF', 'Informant'), ('PLA', 'Plaintiff'), ('RLT', 'Related'), ('SUS', 'Suspect'), ('UNR', 'Unrelated'), ('UNK', 'Unknown'), ('VIC', 'Victim'), ('WIT', 'Witness')], help_text='(Optional) Type of Entity', max_length=3, verbose_name='Type'),
        ),
        migrations.DeleteModel(
            name='HistoricalLinkedCase',
        ),
        migrations.DeleteModel(
            name='LinkedCase',
        ),
    ]
