# Generated by Django 2.0.3 on 2018-07-28 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0006_auto_20180728_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casecompany',
            name='company',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='entity.Company', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='caseperson',
            name='person',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='entity.Person', verbose_name='Person'),
        ),
        migrations.AlterField(
            model_name='historicalcasecompany',
            name='company',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='entity.Company'),
        ),
    ]
