# Generated by Django 2.0.3 on 2018-12-15 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0006_auto_20181209_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='image_upload',
            field=models.FileField(blank=True, help_text='Upload an image for the Case', null=True, upload_to='uploads/', verbose_name='Image'),
        ),
    ]
