# Generated by Django 2.0.3 on 2018-07-28 22:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_auto_20180729_0850'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entity', '0019_auto_20180728_1136'),
        ('case', '0007_auto_20180728_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseDevice',
            fields=[
                ('device_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventory.Device')),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='case.Case', verbose_name='Case')),
            ],
            options={
                'verbose_name': 'Case Device',
                'verbose_name_plural': 'Case Devices',
            },
            bases=('inventory.device',),
        ),
        migrations.CreateModel(
            name='HistoricalCaseDevice',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('description', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Description')),
                ('private', models.BooleanField(default=False, verbose_name='Private')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Device Title')),
                ('make', models.CharField(blank=True, max_length=200, null=True, verbose_name='Device Make')),
                ('model', models.CharField(blank=True, max_length=200, null=True, verbose_name='Device Model')),
                ('purpose', models.CharField(blank=True, max_length=200, null=True, verbose_name='Device Purpose')),
                ('variation', models.CharField(blank=True, max_length=200, null=True, verbose_name='Device Variation')),
                ('serial_number', models.CharField(blank=True, max_length=200, null=True, verbose_name='Serial Number')),
                ('condition', models.CharField(choices=[('EX', 'Excellent'), ('GD', 'Good'), ('AV', 'Average'), ('BA', 'Below Average'), ('PR', 'Poor'), ('DM', 'Damaged'), ('RE', 'Replacement Required'), ('MI', 'Missing')], default='EX', max_length=2, verbose_name='Device Codition')),
                ('returnable', models.BooleanField(default=True, verbose_name='Returnable To Stock')),
                ('service_id', models.CharField(blank=True, max_length=45, null=True, verbose_name='Device Service ID')),
                ('model_number', models.CharField(blank=True, max_length=16, null=True, verbose_name='Device Model Number')),
                ('warranty_title', models.CharField(blank=True, max_length=64, null=True, verbose_name='Warranty Title')),
                ('warranty_contact', models.CharField(blank=True, max_length=128, null=True, verbose_name='Warranty Contract')),
                ('warranty_duration', models.CharField(blank=True, max_length=16, null=True, verbose_name='Warranty Duration')),
                ('warranty_id', models.CharField(blank=True, max_length=45, null=True, verbose_name='Warranty ID')),
                ('warranty_terms', models.CharField(blank=True, max_length=64, null=True, verbose_name='Warranty Terms and Conditions')),
                ('warranty_start', models.DateTimeField(blank=True, null=True, verbose_name='Warranty Start Date')),
                ('warranty_end', models.DateTimeField(blank=True, null=True, verbose_name='Warranty End Date')),
                ('warranty_extended', models.BooleanField(default=False, verbose_name='Extended Warranty')),
                ('purchased', models.DateTimeField(blank=True, null=True, verbose_name='Purchase Date')),
                ('slug', models.SlugField(blank=True, editable=False, null=True, verbose_name='Device Slug')),
                ('created', models.DateTimeField(editable=False, verbose_name='Creation date and time')),
                ('modified', models.DateTimeField(editable=False, null=True, verbose_name='Modification date and time')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('authorisation', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.DeviceAuthorisation')),
                ('case', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='case.Case')),
                ('category', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.DeviceCategory')),
                ('classification', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.DeviceClassification')),
                ('device_ptr', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.Device')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('manufacturer', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='entity.Company')),
                ('rep', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='entity.Person')),
                ('resposible_party', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('service_contract', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.ServiceContract')),
                ('status', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.DeviceStatus')),
                ('type', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.DeviceType')),
                ('vendor', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='entity.Company')),
                ('warranty_responsible', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('warranty_vendor', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='entity.Company')),
            ],
            options={
                'verbose_name': 'historical Case Device',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
        ),
    ]
