# Generated by Django 2.0.3 on 2018-12-16 01:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0007_auto_20181215_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='caseevent',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 16, 1, 44, 3, 486425, tzinfo=utc), help_text='Select a date for the Task', verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='historicalcaseevent',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 16, 1, 44, 3, 486425, tzinfo=utc), help_text='Select a date for the Task', verbose_name='Date'),
        ),
    ]
