# Generated by Django 2.0.3 on 2018-07-28 23:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0006_auto_20180729_0850'),
        ('case', '0008_casedevice_historicalcasedevice'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseInventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decription', models.TextField(max_length=1000, verbose_name='Description')),
                ('reason', models.TextField(max_length=1000, verbose_name='Reason')),
                ('expected_use', models.TextField(max_length=1000, verbose_name='Expected Use Time')),
                ('created', models.DateTimeField(editable=False, verbose_name='Creation date and time')),
                ('modified', models.DateTimeField(editable=False, null=True, verbose_name='Modification date and time')),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case', to='case.Case', verbose_name='Case')),
                ('device', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='device', to='inventory.Device', verbose_name='Device')),
                ('linked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='casedevice_linked_by', to=settings.AUTH_USER_MODEL, verbose_name='Linked By')),
            ],
            options={
                'verbose_name': 'Case Device',
                'verbose_name_plural': 'Case Devices',
            },
        ),
        migrations.CreateModel(
            name='HistoricalCaseInventory',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('decription', models.TextField(max_length=1000, verbose_name='Description')),
                ('reason', models.TextField(max_length=1000, verbose_name='Reason')),
                ('expected_use', models.TextField(max_length=1000, verbose_name='Expected Use Time')),
                ('created', models.DateTimeField(editable=False, verbose_name='Creation date and time')),
                ('modified', models.DateTimeField(editable=False, null=True, verbose_name='Modification date and time')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('case', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='case.Case')),
                ('device', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.Device')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('linked_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Case Device',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
        ),
    ]
