# Generated by Django 2.0.3 on 2019-05-04 02:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0008_auto_20190504_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseevent',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 4, 2, 49, 54, 318563, tzinfo=utc), help_text='Select a date for the Task', verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='historicalcaseevent',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 4, 2, 49, 54, 318563, tzinfo=utc), help_text='Select a date for the Task', verbose_name='Date'),
        ),
    ]
