# Generated by Django 2.0.3 on 2018-12-16 02:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0009_auto_20181216_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseevent',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 16, 2, 53, 0, 92864, tzinfo=utc), help_text='Select a date for the Task', verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='historicalcaseevent',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 16, 2, 53, 0, 92864, tzinfo=utc), help_text='Select a date for the Task', verbose_name='Date'),
        ),
    ]
