# Generated by Django 2.0.3 on 2018-12-16 06:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0010_auto_20181216_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseevent',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 16, 6, 48, 14, 213308, tzinfo=utc), help_text='Select a date for the Task', verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='historicalcaseevent',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 16, 6, 48, 14, 213308, tzinfo=utc), help_text='Select a date for the Task', verbose_name='Date'),
        ),
    ]
