# Generated by Django 2.0.3 on 2018-08-11 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0019_auto_20180728_1136'),
        ('case', '0011_caseevent_historicalcaseevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Description')),
                ('created', models.DateTimeField(editable=False, verbose_name='Creation date and time')),
                ('modified', models.DateTimeField(editable=False, null=True, verbose_name='Modification date and time')),
                ('private', models.BooleanField(default=False, verbose_name='Private')),
                ('role', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Role')),
                ('notes', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Notes')),
                ('type', models.CharField(choices=[('RL', 'Related'), ('UR', 'Unrelated'), ('UN', 'Unknown'), ('SU', 'Suspect'), ('IN', 'Informant'), ('AQ', 'Acquaintance'), ('VI', 'Victim'), ('WK', 'Working'), ('AS', 'Assisting')], default='UN', max_length=2, verbose_name='Type')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entity.Company')),
            ],
            options={
                'verbose_name': 'Case Entity',
                'verbose_name_plural': 'Case Entities',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EventPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Description')),
                ('created', models.DateTimeField(editable=False, verbose_name='Creation date and time')),
                ('modified', models.DateTimeField(editable=False, null=True, verbose_name='Modification date and time')),
                ('private', models.BooleanField(default=False, verbose_name='Private')),
                ('role', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Role')),
                ('notes', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Notes')),
                ('type', models.CharField(choices=[('RL', 'Related'), ('UR', 'Unrelated'), ('UN', 'Unknown'), ('SU', 'Suspect'), ('IN', 'Informant'), ('AQ', 'Acquaintance'), ('VI', 'Victim'), ('WK', 'Working'), ('AS', 'Assisting')], default='UN', max_length=2, verbose_name='Type')),
            ],
            options={
                'verbose_name': 'Case Entity',
                'verbose_name_plural': 'Case Entities',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='caseevent',
            name='evidence',
            field=models.ManyToManyField(blank=True, related_name='event_linked_evidence', to='case.CaseEvidence', verbose_name='Evidence Involved'),
        ),
        migrations.AddField(
            model_name='casetask',
            name='company',
            field=models.ManyToManyField(blank=True, related_name='task_linked_company', to='case.CaseCompany', verbose_name='Companies Involved'),
        ),
        migrations.AddField(
            model_name='casetask',
            name='event',
            field=models.ManyToManyField(blank=True, related_name='task_linked_event', to='case.CaseEvent', verbose_name='Events'),
        ),
        migrations.AddField(
            model_name='casetask',
            name='evidence',
            field=models.ManyToManyField(blank=True, related_name='task_linked_evidence', to='case.CaseEvidence', verbose_name='Evidence Involved'),
        ),
        migrations.AddField(
            model_name='casetask',
            name='inventory',
            field=models.ManyToManyField(blank=True, related_name='task_linked_inventory', to='case.CaseInventory', verbose_name='Inventory Involved'),
        ),
        migrations.AddField(
            model_name='casetask',
            name='note',
            field=models.ManyToManyField(blank=True, related_name='task_linked_note', to='case.CaseNote', verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='casetask',
            name='person',
            field=models.ManyToManyField(blank=True, related_name='task_linked_person', to='case.CasePerson', verbose_name='People Involved'),
        ),
        migrations.AddField(
            model_name='eventperson',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='case.CaseEvent'),
        ),
        migrations.AddField(
            model_name='eventperson',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entity.Person'),
        ),
        migrations.AddField(
            model_name='eventcompany',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='case.CaseEvent'),
        ),
        migrations.AddField(
            model_name='caseevent',
            name='company',
            field=models.ManyToManyField(blank=True, related_name='event_linked_company', through='case.EventCompany', to='entity.Company', verbose_name='Companies Involved'),
        ),
        migrations.AddField(
            model_name='caseevent',
            name='person',
            field=models.ManyToManyField(blank=True, related_name='event_linked_person', through='case.EventPerson', to='entity.Person', verbose_name='People Involved'),
        ),
    ]
