# Generated by Django 2.0.3 on 2018-08-12 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0012_auto_20180811_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='caseinventory',
            name='private',
            field=models.BooleanField(default=False, verbose_name='Private'),
        ),
        migrations.AddField(
            model_name='historicalcaseinventory',
            name='private',
            field=models.BooleanField(default=False, verbose_name='Private'),
        ),
        migrations.AlterField(
            model_name='caseinventory',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='historicalcaseinventory',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Description'),
        ),
    ]
