# Generated by Django 2.0.3 on 2018-07-27 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalservicecontract',
            name='model_number',
        ),
        migrations.RemoveField(
            model_name='servicecontract',
            name='model_number',
        ),
        migrations.AlterField(
            model_name='device',
            name='warranty_vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warranty_vendor', to='entity.Company', verbose_name='Warranty Vendor'),
        ),
        migrations.AlterField(
            model_name='historicaldevice',
            name='warranty_vendor',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='entity.Company'),
        ),
    ]
