# Generated by Django 2.0.3 on 2018-07-27 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20180727_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalservicecontract',
            name='contact',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Contract Contact'),
        ),
        migrations.AlterField(
            model_name='historicalservicecontract',
            name='service_id',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Service ID'),
        ),
        migrations.AlterField(
            model_name='historicalservicecontract',
            name='vendor',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Contract Vendor'),
        ),
        migrations.AlterField(
            model_name='servicecontract',
            name='contact',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Contract Contact'),
        ),
        migrations.AlterField(
            model_name='servicecontract',
            name='service_id',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Service ID'),
        ),
        migrations.AlterField(
            model_name='servicecontract',
            name='vendor',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Contract Vendor'),
        ),
    ]
