# Generated by Django 2.0.3 on 2018-07-27 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20180727_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='purchased',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Purchase Date'),
        ),
        migrations.AlterField(
            model_name='device',
            name='warranty_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Warranty End Date'),
        ),
        migrations.AlterField(
            model_name='device',
            name='warranty_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Warranty Start Date'),
        ),
        migrations.AlterField(
            model_name='historicaldevice',
            name='purchased',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Purchase Date'),
        ),
        migrations.AlterField(
            model_name='historicaldevice',
            name='warranty_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Warranty End Date'),
        ),
        migrations.AlterField(
            model_name='historicaldevice',
            name='warranty_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Warranty Start Date'),
        ),
    ]
