# Generated by Django 2.0.3 on 2018-12-08 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20181208_1958'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalservice',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Service History'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Service History', 'verbose_name_plural': 'Service History'},
        ),
        migrations.AlterField(
            model_name='device',
            name='condition',
            field=models.CharField(choices=[('NW', 'New'), ('EX', 'Excellent'), ('GD', 'Good'), ('AV', 'Average'), ('BA', 'Below Average'), ('PO', 'Poor'), ('DM', 'Damaged'), ('MI', 'Missing')], help_text='Select the condition of the Device', max_length=2, verbose_name='Device Condition'),
        ),
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.CharField(choices=[('CR', 'Checked In - Ready'), ('CN', 'Checked In - Not Ready'), ('CO', 'Checked Out'), ('AL', 'Awaiting Loan Approval'), ('AR', 'Awaiting Return Approval'), ('ST', 'In Storage'), ('DM', 'Damaged'), ('RE', 'Replacement Required'), ('MI', 'Missing'), ('DE', 'Decommisioned'), ('OB', 'Obselete'), ('RS', 'Restricted Use'), ('HOL', 'On Hold'), ('SE', 'Servicing')], help_text='Select the status of the Device', max_length=2, verbose_name='Device Status'),
        ),
        migrations.AlterField(
            model_name='historicaldevice',
            name='condition',
            field=models.CharField(choices=[('NW', 'New'), ('EX', 'Excellent'), ('GD', 'Good'), ('AV', 'Average'), ('BA', 'Below Average'), ('PO', 'Poor'), ('DM', 'Damaged'), ('MI', 'Missing')], help_text='Select the condition of the Device', max_length=2, verbose_name='Device Condition'),
        ),
        migrations.AlterField(
            model_name='historicaldevice',
            name='status',
            field=models.CharField(choices=[('CR', 'Checked In - Ready'), ('CN', 'Checked In - Not Ready'), ('CO', 'Checked Out'), ('AL', 'Awaiting Loan Approval'), ('AR', 'Awaiting Return Approval'), ('ST', 'In Storage'), ('DM', 'Damaged'), ('RE', 'Replacement Required'), ('MI', 'Missing'), ('DE', 'Decommisioned'), ('OB', 'Obselete'), ('RS', 'Restricted Use'), ('HOL', 'On Hold'), ('SE', 'Servicing')], help_text='Select the status of the Device', max_length=2, verbose_name='Device Status'),
        ),
        migrations.AlterField(
            model_name='historicalservice',
            name='status',
            field=models.CharField(choices=[('AW', 'Awaiting Service'), ('SE', 'Being Serviced'), ('AR', 'Awaiting Return'), ('RF', 'Returned From Service'), ('RT', 'Returned To Stock'), ('ST', 'In Storage'), ('RE', 'Replacement Required'), ('MI', 'Missing'), ('DE', 'Decommisioned'), ('OB', 'Obselete'), ('HOL', 'On Hold')], help_text='Select the sservice status', max_length=2, verbose_name='Service Status'),
        ),
        migrations.AlterField(
            model_name='service',
            name='status',
            field=models.CharField(choices=[('AW', 'Awaiting Service'), ('SE', 'Being Serviced'), ('AR', 'Awaiting Return'), ('RF', 'Returned From Service'), ('RT', 'Returned To Stock'), ('ST', 'In Storage'), ('RE', 'Replacement Required'), ('MI', 'Missing'), ('DE', 'Decommisioned'), ('OB', 'Obselete'), ('HOL', 'On Hold')], help_text='Select the sservice status', max_length=2, verbose_name='Service Status'),
        ),
    ]
