# Generated by Django 2.0.3 on 2018-12-16 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20181209_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='condition',
            field=models.CharField(choices=[('AV', 'Average'), ('BA', 'Below Average'), ('DM', 'Damaged'), ('EX', 'Excellent'), ('GD', 'Good'), ('LO', 'Lost'), ('MI', 'Missing'), ('NW', 'New'), ('PO', 'Poor')], help_text='Select the condition of the Device', max_length=2, verbose_name='Device Condition'),
        ),
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.CharField(choices=[('CR', 'Checked In - Ready'), ('CN', 'Checked In - Not Ready'), ('CO', 'Checked Out'), ('DM', 'Damaged'), ('DE', 'Decommisioned'), ('HOL', 'On Hold'), ('LP', 'Awaiting Loan Approval'), ('MI', 'Missing'), ('OB', 'Obselete'), ('RE', 'Replacement Required'), ('RP', 'Awaiting Return Approval'), ('RS', 'Restricted Use'), ('SE', 'Servicing'), ('ST', 'In Storage')], help_text='Select the status of the Device', max_length=2, verbose_name='Device Status'),
        ),
        migrations.AlterField(
            model_name='historicaldevice',
            name='condition',
            field=models.CharField(choices=[('AV', 'Average'), ('BA', 'Below Average'), ('DM', 'Damaged'), ('EX', 'Excellent'), ('GD', 'Good'), ('LO', 'Lost'), ('MI', 'Missing'), ('NW', 'New'), ('PO', 'Poor')], help_text='Select the condition of the Device', max_length=2, verbose_name='Device Condition'),
        ),
        migrations.AlterField(
            model_name='historicaldevice',
            name='status',
            field=models.CharField(choices=[('CR', 'Checked In - Ready'), ('CN', 'Checked In - Not Ready'), ('CO', 'Checked Out'), ('DM', 'Damaged'), ('DE', 'Decommisioned'), ('HOL', 'On Hold'), ('LP', 'Awaiting Loan Approval'), ('MI', 'Missing'), ('OB', 'Obselete'), ('RE', 'Replacement Required'), ('RP', 'Awaiting Return Approval'), ('RS', 'Restricted Use'), ('SE', 'Servicing'), ('ST', 'In Storage')], help_text='Select the status of the Device', max_length=2, verbose_name='Device Status'),
        ),
    ]
