# Generated by Django 2.0.3 on 2018-07-28 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20180728_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manufacturer', to='entity.Company', verbose_name='Device Manufacturer'),
        ),
        migrations.AlterField(
            model_name='device',
            name='rep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_rep', to='entity.Person', verbose_name='Vendor Sales Rep'),
        ),
    ]
