# Generated by Django 2.0.3 on 2018-12-16 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20181216_1252'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalservice',
            old_name='serviced_by',
            new_name='vendor',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='serviced_by',
            new_name='vendor',
        ),
    ]
