# Generated by Django 2.0.3 on 2018-07-28 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20180728_1136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalstorage',
            name='device',
        ),
        migrations.RemoveField(
            model_name='historicalstorage',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='storage',
            name='device',
        ),
        migrations.DeleteModel(
            name='HistoricalStorage',
        ),
        migrations.DeleteModel(
            name='Storage',
        ),
    ]
