# Generated by Django 2.0.3 on 2018-08-12 03:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0006_auto_20180729_0850'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Description')),
                ('created', models.DateTimeField(editable=False, verbose_name='Creation date and time')),
                ('modified', models.DateTimeField(editable=False, null=True, verbose_name='Modification date and time')),
                ('private', models.BooleanField(default=False, verbose_name='Private')),
                ('text', models.TextField(max_length=1000, verbose_name='Comment')),
                ('case_id', models.IntegerField(blank=True, max_length=16, null=True, verbose_name='Case')),
            ],
            options={
                'verbose_name': 'Device Comment',
                'verbose_name_plural': 'Device Comments',
            },
        ),
        migrations.CreateModel(
            name='HistoricalComment',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('description', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Description')),
                ('created', models.DateTimeField(editable=False, verbose_name='Creation date and time')),
                ('modified', models.DateTimeField(editable=False, null=True, verbose_name='Modification date and time')),
                ('private', models.BooleanField(default=False, verbose_name='Private')),
                ('text', models.TextField(max_length=1000, verbose_name='Comment')),
                ('case_id', models.IntegerField(blank=True, max_length=16, null=True, verbose_name='Case')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Device Comment',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
        ),
        migrations.CreateModel(
            name='HistoricalLoan',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('description', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Description')),
                ('created', models.DateTimeField(editable=False, verbose_name='Creation date and time')),
                ('modified', models.DateTimeField(editable=False, null=True, verbose_name='Modification date and time')),
                ('private', models.BooleanField(default=False, verbose_name='Private')),
                ('reason', models.TextField(max_length=1000, verbose_name='Reason')),
                ('expected_use', models.TextField(max_length=1000, verbose_name='Expected Use Time')),
                ('case_id', models.IntegerField(blank=True, max_length=16, null=True, verbose_name='Case')),
                ('condition', models.CharField(choices=[('NW', 'New'), ('EX', 'Excellent'), ('GD', 'Good'), ('AV', 'Average'), ('BA', 'Below Average'), ('PR', 'Poor'), ('DM', 'Damaged'), ('LO', 'Lost')], default='EX', max_length=2, verbose_name='Device Condition')),
                ('returned', models.BooleanField(default=False, verbose_name='Returned')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Device Loan',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Description')),
                ('created', models.DateTimeField(editable=False, verbose_name='Creation date and time')),
                ('modified', models.DateTimeField(editable=False, null=True, verbose_name='Modification date and time')),
                ('private', models.BooleanField(default=False, verbose_name='Private')),
                ('reason', models.TextField(max_length=1000, verbose_name='Reason')),
                ('expected_use', models.TextField(max_length=1000, verbose_name='Expected Use Time')),
                ('case_id', models.IntegerField(blank=True, max_length=16, null=True, verbose_name='Case')),
                ('condition', models.CharField(choices=[('NW', 'New'), ('EX', 'Excellent'), ('GD', 'Good'), ('AV', 'Average'), ('BA', 'Below Average'), ('PR', 'Poor'), ('DM', 'Damaged'), ('LO', 'Lost')], default='EX', max_length=2, verbose_name='Device Condition')),
                ('returned', models.BooleanField(default=False, verbose_name='Returned')),
            ],
            options={
                'verbose_name': 'Device Loan',
                'verbose_name_plural': 'Device Loans',
            },
        ),
        migrations.CreateModel(
            name='LoanRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Description')),
                ('created', models.DateTimeField(editable=False, verbose_name='Creation date and time')),
                ('modified', models.DateTimeField(editable=False, null=True, verbose_name='Modification date and time')),
                ('private', models.BooleanField(default=False, verbose_name='Private')),
                ('reason', models.TextField(max_length=1000, verbose_name='Reason')),
                ('case_id', models.IntegerField(blank=True, null=True, verbose_name='Case')),
                ('status', models.CharField(choices=[('PE', 'Pending'), ('AP', 'Approved'), ('RE', 'Rejected'), ('HO', 'On Hold'), ('WI', 'Withdrawn')], default='PE', max_length=2, verbose_name='Status')),
                ('expected_use', models.TextField(max_length=1000, verbose_name='Expected Use Time')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_approved_by', to=settings.AUTH_USER_MODEL, verbose_name='Approved By')),
            ],
            options={
                'verbose_name': 'Loan Request',
                'verbose_name_plural': 'Loan Requests',
            },
        ),
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Description')),
                ('created', models.DateTimeField(editable=False, verbose_name='Creation date and time')),
                ('modified', models.DateTimeField(editable=False, null=True, verbose_name='Modification date and time')),
                ('private', models.BooleanField(default=False, verbose_name='Private')),
                ('reason', models.TextField(max_length=1000, verbose_name='Reason')),
                ('case_id', models.IntegerField(blank=True, null=True, verbose_name='Case')),
                ('status', models.CharField(choices=[('PE', 'Pending'), ('AP', 'Approved'), ('RE', 'Rejected'), ('HO', 'On Hold'), ('WI', 'Withdrawn')], default='PE', max_length=2, verbose_name='Status')),
                ('actual_use', models.TextField(max_length=1000, verbose_name='Actual Use Time')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_approved_by', to=settings.AUTH_USER_MODEL, verbose_name='Approved By')),
            ],
            options={
                'verbose_name': 'Return Request',
                'verbose_name_plural': 'Return Requests',
            },
        ),
        migrations.AddField(
            model_name='historicalservice',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Creation date and time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalservice',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='historicalservice',
            name='modified',
            field=models.DateTimeField(editable=False, null=True, verbose_name='Modification date and time'),
        ),
        migrations.AddField(
            model_name='historicalservice',
            name='private',
            field=models.BooleanField(default=False, verbose_name='Private'),
        ),
        migrations.AddField(
            model_name='service',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Creation date and time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='service',
            name='modified',
            field=models.DateTimeField(editable=False, null=True, verbose_name='Modification date and time'),
        ),
        migrations.AddField(
            model_name='service',
            name='private',
            field=models.BooleanField(default=False, verbose_name='Private'),
        ),
        migrations.AlterField(
            model_name='device',
            name='condition',
            field=models.CharField(choices=[('NW', 'New'), ('EX', 'Excellent'), ('GD', 'Good'), ('AV', 'Average'), ('BA', 'Below Average'), ('PR', 'Poor'), ('DM', 'Damaged'), ('LO', 'Lost')], default='EX', max_length=2, verbose_name='Device Condition'),
        ),
        migrations.AlterField(
            model_name='historicaldevice',
            name='condition',
            field=models.CharField(choices=[('NW', 'New'), ('EX', 'Excellent'), ('GD', 'Good'), ('AV', 'Average'), ('BA', 'Below Average'), ('PR', 'Poor'), ('DM', 'Damaged'), ('LO', 'Lost')], default='EX', max_length=2, verbose_name='Device Condition'),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='device',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='return_request_device', to='inventory.Device', verbose_name='Device'),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='loan',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='device_loan', to='inventory.Loan', verbose_name='Loan'),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_requested_by', to=settings.AUTH_USER_MODEL, verbose_name='Requested By'),
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='device',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='loan_request_device', to='inventory.Device', verbose_name='Device'),
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_requested_by', to=settings.AUTH_USER_MODEL, verbose_name='Requested By'),
        ),
        migrations.AddField(
            model_name='loan',
            name='device',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='loan_device', to='inventory.Device', verbose_name='Device'),
        ),
        migrations.AddField(
            model_name='loan',
            name='loaned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loaned_by', to=settings.AUTH_USER_MODEL, verbose_name='Loaned By'),
        ),
        migrations.AddField(
            model_name='loan',
            name='loaned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loaned_to', to=settings.AUTH_USER_MODEL, verbose_name='Loaned To'),
        ),
        migrations.AddField(
            model_name='historicalloan',
            name='device',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.Device'),
        ),
        migrations.AddField(
            model_name='historicalloan',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalloan',
            name='loaned_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalloan',
            name='loaned_to',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcomment',
            name='device',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.Device'),
        ),
        migrations.AddField(
            model_name='historicalcomment',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcomment',
            name='user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_device', to='inventory.Device', verbose_name='Comment Device'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_user', to=settings.AUTH_USER_MODEL, verbose_name='Comment User'),
        ),
    ]
