# Generated by Django 2.0.3 on 2018-08-12 03:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_auto_20180812_1329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalloan',
            name='expected_use',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='expected_use',
        ),
        migrations.RemoveField(
            model_name='loanrequest',
            name='expected_use',
        ),
        migrations.AddField(
            model_name='historicalloan',
            name='booked_from',
            field=models.TextField(default=django.utils.timezone.now, max_length=100, verbose_name='Booked From'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalloan',
            name='booked_until',
            field=models.TextField(default=django.utils.timezone.now, max_length=100, verbose_name='Booked Until'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loan',
            name='booked_from',
            field=models.TextField(default=django.utils.timezone.now, max_length=100, verbose_name='Booked From'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loan',
            name='booked_until',
            field=models.TextField(default=django.utils.timezone.now, max_length=100, verbose_name='Booked Until'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='booked_from',
            field=models.TextField(default=django.utils.timezone.now, max_length=1000, verbose_name='Booked From'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='booked_until',
            field=models.TextField(default=django.utils.timezone.now, max_length=1000, verbose_name='Booked Until'),
            preserve_default=False,
        ),
    ]
