# Generated by Django 2.0.3 on 2018-08-12 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_auto_20180812_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='case_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Case'),
        ),
        migrations.AlterField(
            model_name='historicalcomment',
            name='case_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Case'),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='booked_from',
            field=models.TextField(max_length=100, verbose_name='Booked From'),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='booked_until',
            field=models.TextField(max_length=100, verbose_name='Booked Until'),
        ),
    ]
