# Generated by Django 2.0.3 on 2018-08-12 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_auto_20180812_1351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalloan',
            name='device',
        ),
        migrations.RemoveField(
            model_name='historicalloan',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalloan',
            name='loaned_by',
        ),
        migrations.RemoveField(
            model_name='historicalloan',
            name='loaned_to',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='device',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='loaned_by',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='loaned_to',
        ),
        migrations.RemoveField(
            model_name='loanrequest',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='loanrequest',
            name='device',
        ),
        migrations.RemoveField(
            model_name='loanrequest',
            name='requested_by',
        ),
        migrations.RemoveField(
            model_name='returnrequest',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='returnrequest',
            name='device',
        ),
        migrations.RemoveField(
            model_name='returnrequest',
            name='loan',
        ),
        migrations.RemoveField(
            model_name='returnrequest',
            name='requested_by',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='case_id',
        ),
        migrations.RemoveField(
            model_name='historicalcomment',
            name='case_id',
        ),
        migrations.DeleteModel(
            name='HistoricalLoan',
        ),
        migrations.DeleteModel(
            name='Loan',
        ),
        migrations.DeleteModel(
            name='LoanRequest',
        ),
        migrations.DeleteModel(
            name='ReturnRequest',
        ),
    ]
