# Generated by Django 2.0.3 on 2018-07-22 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='noteauthorisation',
            name='private',
            field=models.BooleanField(default=False, verbose_name='Private'),
        ),
        migrations.AddField(
            model_name='notecategory',
            name='private',
            field=models.BooleanField(default=False, verbose_name='Private'),
        ),
        migrations.AddField(
            model_name='noteclassification',
            name='private',
            field=models.BooleanField(default=False, verbose_name='Private'),
        ),
        migrations.AddField(
            model_name='notepriority',
            name='private',
            field=models.BooleanField(default=False, verbose_name='Private'),
        ),
        migrations.AddField(
            model_name='notestatus',
            name='private',
            field=models.BooleanField(default=False, verbose_name='Private'),
        ),
        migrations.AddField(
            model_name='notestatusgroup',
            name='private',
            field=models.BooleanField(default=False, verbose_name='Private'),
        ),
        migrations.AddField(
            model_name='notetype',
            name='private',
            field=models.BooleanField(default=False, verbose_name='Private'),
        ),
    ]
