# Generated by Django 2.0.3 on 2018-07-26 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskAuthorisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Description')),
                ('created', models.DateTimeField(editable=False, verbose_name='Creation date and time')),
                ('modified', models.DateTimeField(editable=False, null=True, verbose_name='Modification date and time')),
                ('private', models.BooleanField(default=False, verbose_name='Private')),
                ('title', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Authorisation')),
            ],
            options={
                'verbose_name': 'Task Authorisation',
                'verbose_name_plural': 'Task Authorisations',
            },
        ),
        migrations.CreateModel(
            name='TaskCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Description')),
                ('created', models.DateTimeField(editable=False, verbose_name='Creation date and time')),
                ('modified', models.DateTimeField(editable=False, null=True, verbose_name='Modification date and time')),
                ('private', models.BooleanField(default=False, verbose_name='Private')),
                ('title', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Task Category',
                'verbose_name_plural': 'Task Categories',
            },
        ),
        migrations.CreateModel(
            name='TaskClassification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Description')),
                ('created', models.DateTimeField(editable=False, verbose_name='Creation date and time')),
                ('modified', models.DateTimeField(editable=False, null=True, verbose_name='Modification date and time')),
                ('private', models.BooleanField(default=False, verbose_name='Private')),
                ('title', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Classification')),
            ],
            options={
                'verbose_name': 'Task Classification',
                'verbose_name_plural': 'Task Classifications',
            },
        ),
        migrations.CreateModel(
            name='TaskPriority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Description')),
                ('created', models.DateTimeField(editable=False, verbose_name='Creation date and time')),
                ('modified', models.DateTimeField(editable=False, null=True, verbose_name='Modification date and time')),
                ('private', models.BooleanField(default=False, verbose_name='Private')),
                ('title', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Priority')),
                ('colour', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Colour')),
            ],
            options={
                'verbose_name': 'Task Priority',
                'verbose_name_plural': 'Task Priorities',
            },
        ),
        migrations.CreateModel(
            name='TaskStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Description')),
                ('created', models.DateTimeField(editable=False, verbose_name='Creation date and time')),
                ('modified', models.DateTimeField(editable=False, null=True, verbose_name='Modification date and time')),
                ('private', models.BooleanField(default=False, verbose_name='Private')),
                ('title', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Task Status',
                'verbose_name_plural': 'Task Status',
            },
        ),
        migrations.CreateModel(
            name='TaskStatusGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Description')),
                ('created', models.DateTimeField(editable=False, verbose_name='Creation date and time')),
                ('modified', models.DateTimeField(editable=False, null=True, verbose_name='Modification date and time')),
                ('private', models.BooleanField(default=False, verbose_name='Private')),
                ('title', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Status Group')),
                ('status', models.ManyToManyField(blank=True, to='task.TaskStatus', verbose_name='Task Status')),
            ],
            options={
                'verbose_name': 'Task Status Group',
                'verbose_name_plural': 'Task Status Groups',
            },
        ),
        migrations.CreateModel(
            name='TaskType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Description')),
                ('created', models.DateTimeField(editable=False, verbose_name='Creation date and time')),
                ('modified', models.DateTimeField(editable=False, null=True, verbose_name='Modification date and time')),
                ('private', models.BooleanField(default=False, verbose_name='Private')),
                ('title', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Type')),
            ],
            options={
                'verbose_name': 'Task Type',
                'verbose_name_plural': 'Task Types',
            },
        ),
    ]
