# Generated by Django 2.0.3 on 2018-12-08 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0002_auto_20181208_1511'),
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaltaskclassification',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicaltasktype',
            name='history_user',
        ),
        migrations.DeleteModel(
            name='TaskClassification',
        ),
        migrations.DeleteModel(
            name='TaskType',
        ),
        migrations.AlterField(
            model_name='historicaltaskcategory',
            name='colour',
            field=models.CharField(blank=True, default=None, help_text='(Optional) Enter a Hexidecimal colour representation', max_length=7, null=True, verbose_name='Colour'),
        ),
        migrations.AlterField(
            model_name='historicaltaskcategory',
            name='created',
            field=models.DateTimeField(editable=False, help_text='The creation date', verbose_name='Creation Date'),
        ),
        migrations.AlterField(
            model_name='historicaltaskcategory',
            name='description',
            field=models.CharField(blank=True, default=None, help_text='(Optional) Enter a description', max_length=250, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='historicaltaskcategory',
            name='modified',
            field=models.DateTimeField(editable=False, help_text='The mdification date', null=True, verbose_name='Modification date'),
        ),
        migrations.AlterField(
            model_name='historicaltaskcategory',
            name='title',
            field=models.CharField(default=None, help_text='Enter a title', max_length=50, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='historicaltaskpriority',
            name='colour',
            field=models.CharField(blank=True, default=None, help_text='(Optional) Enter a Hexidecimal colour representation', max_length=7, null=True, verbose_name='Colour'),
        ),
        migrations.AlterField(
            model_name='historicaltaskpriority',
            name='created',
            field=models.DateTimeField(editable=False, help_text='The creation date', verbose_name='Creation Date'),
        ),
        migrations.AlterField(
            model_name='historicaltaskpriority',
            name='description',
            field=models.CharField(blank=True, default=None, help_text='(Optional) Enter a description', max_length=250, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='historicaltaskpriority',
            name='modified',
            field=models.DateTimeField(editable=False, help_text='The mdification date', null=True, verbose_name='Modification date'),
        ),
        migrations.AlterField(
            model_name='historicaltaskpriority',
            name='title',
            field=models.CharField(default=None, help_text='Enter a title', max_length=50, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='historicaltaskstatus',
            name='colour',
            field=models.CharField(blank=True, default=None, help_text='(Optional) Enter a Hexidecimal colour representation', max_length=7, null=True, verbose_name='Colour'),
        ),
        migrations.AlterField(
            model_name='historicaltaskstatus',
            name='created',
            field=models.DateTimeField(editable=False, help_text='The creation date', verbose_name='Creation Date'),
        ),
        migrations.AlterField(
            model_name='historicaltaskstatus',
            name='description',
            field=models.CharField(blank=True, default=None, help_text='(Optional) Enter a description', max_length=250, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='historicaltaskstatus',
            name='modified',
            field=models.DateTimeField(editable=False, help_text='The mdification date', null=True, verbose_name='Modification date'),
        ),
        migrations.AlterField(
            model_name='historicaltaskstatus',
            name='title',
            field=models.CharField(default=None, help_text='Enter a title', max_length=50, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='historicaltaskstatusgroup',
            name='colour',
            field=models.CharField(blank=True, default=None, help_text='(Optional) Enter a Hexidecimal colour representation', max_length=7, null=True, verbose_name='Colour'),
        ),
        migrations.AlterField(
            model_name='historicaltaskstatusgroup',
            name='created',
            field=models.DateTimeField(editable=False, help_text='The creation date', verbose_name='Creation Date'),
        ),
        migrations.AlterField(
            model_name='historicaltaskstatusgroup',
            name='description',
            field=models.CharField(blank=True, default=None, help_text='(Optional) Enter a description', max_length=250, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='historicaltaskstatusgroup',
            name='modified',
            field=models.DateTimeField(editable=False, help_text='The mdification date', null=True, verbose_name='Modification date'),
        ),
        migrations.AlterField(
            model_name='historicaltaskstatusgroup',
            name='title',
            field=models.CharField(default=None, help_text='Enter a title', max_length=50, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='taskcategory',
            name='colour',
            field=models.CharField(blank=True, default=None, help_text='(Optional) Enter a Hexidecimal colour representation', max_length=7, null=True, verbose_name='Colour'),
        ),
        migrations.AlterField(
            model_name='taskcategory',
            name='created',
            field=models.DateTimeField(editable=False, help_text='The creation date', verbose_name='Creation Date'),
        ),
        migrations.AlterField(
            model_name='taskcategory',
            name='description',
            field=models.CharField(blank=True, default=None, help_text='(Optional) Enter a description', max_length=250, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='taskcategory',
            name='modified',
            field=models.DateTimeField(editable=False, help_text='The mdification date', null=True, verbose_name='Modification date'),
        ),
        migrations.AlterField(
            model_name='taskcategory',
            name='title',
            field=models.CharField(default=None, help_text='Enter a title', max_length=50, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='taskpriority',
            name='colour',
            field=models.CharField(blank=True, default=None, help_text='(Optional) Enter a Hexidecimal colour representation', max_length=7, null=True, verbose_name='Colour'),
        ),
        migrations.AlterField(
            model_name='taskpriority',
            name='created',
            field=models.DateTimeField(editable=False, help_text='The creation date', verbose_name='Creation Date'),
        ),
        migrations.AlterField(
            model_name='taskpriority',
            name='description',
            field=models.CharField(blank=True, default=None, help_text='(Optional) Enter a description', max_length=250, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='taskpriority',
            name='modified',
            field=models.DateTimeField(editable=False, help_text='The mdification date', null=True, verbose_name='Modification date'),
        ),
        migrations.AlterField(
            model_name='taskpriority',
            name='title',
            field=models.CharField(default=None, help_text='Enter a title', max_length=50, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='taskstatus',
            name='colour',
            field=models.CharField(blank=True, default=None, help_text='(Optional) Enter a Hexidecimal colour representation', max_length=7, null=True, verbose_name='Colour'),
        ),
        migrations.AlterField(
            model_name='taskstatus',
            name='created',
            field=models.DateTimeField(editable=False, help_text='The creation date', verbose_name='Creation Date'),
        ),
        migrations.AlterField(
            model_name='taskstatus',
            name='description',
            field=models.CharField(blank=True, default=None, help_text='(Optional) Enter a description', max_length=250, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='taskstatus',
            name='modified',
            field=models.DateTimeField(editable=False, help_text='The mdification date', null=True, verbose_name='Modification date'),
        ),
        migrations.AlterField(
            model_name='taskstatus',
            name='title',
            field=models.CharField(default=None, help_text='Enter a title', max_length=50, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='taskstatusgroup',
            name='colour',
            field=models.CharField(blank=True, default=None, help_text='(Optional) Enter a Hexidecimal colour representation', max_length=7, null=True, verbose_name='Colour'),
        ),
        migrations.AlterField(
            model_name='taskstatusgroup',
            name='created',
            field=models.DateTimeField(editable=False, help_text='The creation date', verbose_name='Creation Date'),
        ),
        migrations.AlterField(
            model_name='taskstatusgroup',
            name='description',
            field=models.CharField(blank=True, default=None, help_text='(Optional) Enter a description', max_length=250, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='taskstatusgroup',
            name='modified',
            field=models.DateTimeField(editable=False, help_text='The mdification date', null=True, verbose_name='Modification date'),
        ),
        migrations.AlterField(
            model_name='taskstatusgroup',
            name='status',
            field=models.ManyToManyField(blank=True, help_text='Select Task Status', to='task.TaskStatus', verbose_name='Task Status'),
        ),
        migrations.AlterField(
            model_name='taskstatusgroup',
            name='title',
            field=models.CharField(default=None, help_text='Enter a title', max_length=50, verbose_name='Title'),
        ),
        migrations.DeleteModel(
            name='HistoricalTaskClassification',
        ),
        migrations.DeleteModel(
            name='HistoricalTaskType',
        ),
    ]
