# Generated by Django 2.0.3 on 2018-07-22 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaltask',
            name='assigned_by',
        ),
        migrations.RemoveField(
            model_name='historicaltask',
            name='authorisation',
        ),
        migrations.RemoveField(
            model_name='historicaltask',
            name='category',
        ),
        migrations.RemoveField(
            model_name='historicaltask',
            name='classification',
        ),
        migrations.RemoveField(
            model_name='historicaltask',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicaltask',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='historicaltask',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='historicaltask',
            name='status',
        ),
        migrations.RemoveField(
            model_name='historicaltask',
            name='type',
        ),
        migrations.RemoveField(
            model_name='task',
            name='assigned_by',
        ),
        migrations.RemoveField(
            model_name='task',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='task',
            name='authorisation',
        ),
        migrations.RemoveField(
            model_name='task',
            name='category',
        ),
        migrations.RemoveField(
            model_name='task',
            name='classification',
        ),
        migrations.RemoveField(
            model_name='task',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='task',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='task',
            name='status',
        ),
        migrations.RemoveField(
            model_name='task',
            name='type',
        ),
        migrations.AddField(
            model_name='taskauthorisation',
            name='private',
            field=models.BooleanField(default=False, verbose_name='Private'),
        ),
        migrations.AddField(
            model_name='taskcategory',
            name='private',
            field=models.BooleanField(default=False, verbose_name='Private'),
        ),
        migrations.AddField(
            model_name='taskclassification',
            name='private',
            field=models.BooleanField(default=False, verbose_name='Private'),
        ),
        migrations.AddField(
            model_name='taskpriority',
            name='private',
            field=models.BooleanField(default=False, verbose_name='Private'),
        ),
        migrations.AddField(
            model_name='taskstatus',
            name='private',
            field=models.BooleanField(default=False, verbose_name='Private'),
        ),
        migrations.AddField(
            model_name='taskstatusgroup',
            name='private',
            field=models.BooleanField(default=False, verbose_name='Private'),
        ),
        migrations.AddField(
            model_name='tasktype',
            name='private',
            field=models.BooleanField(default=False, verbose_name='Private'),
        ),
        migrations.DeleteModel(
            name='HistoricalTask',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
