# Generated by Django 2.0.3 on 2018-06-03 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadModel',
        ),
    ]
