# Generated by Django 2.0.3 on 2018-07-26 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary', models.BooleanField(default=False)),
                ('line1', models.CharField(max_length=255)),
                ('line2', models.CharField(blank=True, max_length=255, null=True)),
                ('line3', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(max_length=255)),
                ('postcode', models.CharField(blank=True, max_length=31)),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
            },
        ),
        migrations.CreateModel(
            name='ContactLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=31)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('code', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Country')),
                ('lat', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Latitude')),
                ('lng', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Longtitude')),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=254)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='entity.ContactLocation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(db_index=True, max_length=255)),
                ('last_name', models.CharField(db_index=True, max_length=255)),
                ('suffix', models.CharField(blank=True, max_length=55)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('slug_first', models.SlugField(editable=False)),
                ('slug_last', models.SlugField(editable=False)),
                ('addresses', models.ManyToManyField(to='entity.Address')),
                ('emails', models.ManyToManyField(to='entity.Email')),
            ],
            options={
                'verbose_name_plural': 'People',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Prefix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary', models.BooleanField(default=False)),
                ('service', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Social Media Service')),
                ('alias', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Social Media Alias')),
                ('url', models.URLField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='entity.ContactLocation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Abbreviation')),
                ('title', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='State')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='entity.Country')),
            ],
            options={
                'verbose_name': 'State',
                'verbose_name_plural': 'States',
            },
        ),
        migrations.CreateModel(
            name='Telephone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary', models.BooleanField(default=False)),
                ('number', models.CharField(db_index=True, max_length=63)),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'Fixed'), (2, 'Mobile'), (3, 'Fax')])),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='entity.ContactLocation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary', models.BooleanField(default=False)),
                ('url', models.URLField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='entity.ContactLocation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='person',
            name='prefix',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='entity.Prefix'),
        ),
        migrations.AddField(
            model_name='person',
            name='telephones',
            field=models.ManyToManyField(to='entity.Telephone'),
        ),
        migrations.AddField(
            model_name='person',
            name='websites',
            field=models.ManyToManyField(to='entity.Website'),
        ),
        migrations.AddField(
            model_name='address',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='entity.ContactLocation'),
        ),
        migrations.AddField(
            model_name='address',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='entity.State'),
        ),
        migrations.AlterUniqueTogether(
            name='state',
            unique_together={('short_name', 'country')},
        ),
    ]
