# Generated by Django 2.0.3 on 2018-07-26 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='location',
            field=models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Social Media Service'),
        ),
        migrations.AlterField(
            model_name='email',
            name='location',
            field=models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Social Media Service'),
        ),
        migrations.AlterField(
            model_name='social',
            name='location',
            field=models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Social Media Service'),
        ),
        migrations.AlterField(
            model_name='telephone',
            name='location',
            field=models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Social Media Service'),
        ),
        migrations.AlterField(
            model_name='website',
            name='location',
            field=models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Social Media Service'),
        ),
        migrations.DeleteModel(
            name='ContactLocation',
        ),
    ]
