# Generated by Django 2.0.3 on 2018-12-01 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyaddress',
            name='location',
        ),
        migrations.RemoveField(
            model_name='historicalcompanyaddress',
            name='location',
        ),
        migrations.AddField(
            model_name='address',
            name='current',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='companyaddress',
            name='current',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='email',
            name='current',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='historicaladdress',
            name='current',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='historicalcompanyaddress',
            name='current',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='historicalemail',
            name='current',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='historicalsocial',
            name='current',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='historicaltelephone',
            name='current',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='historicalwebsite',
            name='current',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='social',
            name='current',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='telephone',
            name='current',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='website',
            name='current',
            field=models.BooleanField(default=True),
        ),
    ]
