# Generated by Django 2.0.3 on 2018-12-01 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0002_auto_20181201_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='address1',
            field=models.ManyToManyField(to='entity.CompanyAddress', verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.ManyToManyField(to='entity.Address', verbose_name='Address'),
        ),
    ]
