# Generated by Django 2.0.3 on 2018-07-26 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0003_auto_20180726_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='prefix',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='entity.Prefix'),
        ),
    ]
