# Generated by Django 2.0.3 on 2018-12-01 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0004_remove_company_address1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompanyAddress',
        ),
        migrations.RemoveField(
            model_name='historicalcompanyaddress',
            name='history_user',
        ),
        migrations.DeleteModel(
            name='HistoricalCompanyAddress',
        ),
    ]
