# Generated by Django 2.0.3 on 2018-07-26 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0007_auto_20180726_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='location',
            field=models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='email',
            name='primary',
            field=models.BooleanField(default=False),
        ),
    ]
