# Generated by Django 2.0.3 on 2018-12-15 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0007_auto_20181215_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalperson',
            name='gender',
            field=models.PositiveIntegerField(blank=True, choices=[('1', 'Unknown'), ('2', 'Male'), ('3', 'Female')], help_text='Select the gender', null=True, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.PositiveIntegerField(blank=True, choices=[('1', 'Unknown'), ('2', 'Male'), ('3', 'Female')], help_text='Select the gender', null=True, verbose_name='Gender'),
        ),
    ]
