# Generated by Django 2.0.3 on 2018-07-27 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0013_remove_person_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='social',
        ),
        migrations.RemoveField(
            model_name='person',
            name='social',
        ),
    ]
