# Generated by Django 2.0.3 on 2018-07-27 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0014_auto_20180727_1342'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='addresse',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='addresses',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='emails',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='telephones',
            new_name='telephone',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='websites',
            new_name='website',
        ),
    ]
