# Generated by Django 2.0.3 on 2018-07-27 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0015_auto_20180727_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='description',
        ),
        migrations.RemoveField(
            model_name='person',
            name='private',
        ),
    ]
