# Generated by Django 2.0.3 on 2018-07-27 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0016_auto_20180727_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='description',
        ),
        migrations.RemoveField(
            model_name='company',
            name='private',
        ),
    ]
