# Generated by Django 2.0.3 on 2018-07-28 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0018_auto_20180727_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='industry',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Industry'),
        ),
        migrations.AddField(
            model_name='company',
            name='primary_market',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Primary Market'),
        ),
        migrations.AlterField(
            model_name='company',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Issuer Code'),
        ),
        migrations.AlterField(
            model_name='company',
            name='notes',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Company Notes'),
        ),
        migrations.AlterField(
            model_name='company',
            name='title',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Company Title'),
        ),
    ]
