# Generated by Django 2.0.3 on 2018-12-15 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20181208_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='prefix',
            field=models.CharField(blank=True, choices=[('1', 'Mr.'), ('2', 'Mrs.')], max_length=10, null=True, verbose_name='Prefix'),
        ),
    ]
