# Generated by Django 2.0.3 on 2019-05-04 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190504_1236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalusercategory',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicaluserstatusgroup',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalusertype',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='userstatusgroup',
            name='status',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='anniversary',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='category',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='height',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='salary',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='type',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='weight',
        ),
        migrations.DeleteModel(
            name='HistoricalUserCategory',
        ),
        migrations.DeleteModel(
            name='HistoricalUserStatusGroup',
        ),
        migrations.DeleteModel(
            name='HistoricalUserType',
        ),
        migrations.DeleteModel(
            name='UserCategory',
        ),
        migrations.DeleteModel(
            name='UserStatusGroup',
        ),
        migrations.DeleteModel(
            name='UserType',
        ),
    ]
