# Generated by Django 2.0.3 on 2018-10-28 06:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20181028_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 28, 6, 5, 59, 215093, tzinfo=utc), editable=False, verbose_name='Creation date and time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='modified',
            field=models.DateTimeField(editable=False, null=True, verbose_name='Modification date and time'),
        ),
    ]
