# Generated by Django 2.0.3 on 2018-12-23 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authorisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, help_text='Enter a title', max_length=50, verbose_name='Title')),
                ('colour', models.CharField(blank=True, default=None, help_text='(Optional) Enter a Hexidecimal colour representation', max_length=7, null=True, verbose_name='Colour')),
                ('description', models.CharField(blank=True, default=None, help_text='(Optional) Enter a description', max_length=250, null=True, verbose_name='Description')),
                ('created', models.DateTimeField(editable=False, help_text='The creation date', verbose_name='Creation Date')),
                ('modified', models.DateTimeField(editable=False, help_text='The mdification date', null=True, verbose_name='Modification date')),
                ('level', models.IntegerField(default=None, help_text='Enter a level', verbose_name='Level')),
            ],
            options={
                'verbose_name': 'Authorisation',
                'verbose_name_plural': 'Authorisation',
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(default=None, help_text='Enter a note', max_length=5000, verbose_name='Note')),
                ('private', models.BooleanField(default=False, help_text='(Optional) Is Private', verbose_name='Private')),
                ('created', models.DateTimeField(editable=False, help_text='The creation date', verbose_name='Creation Date')),
                ('modified', models.DateTimeField(editable=False, help_text='The mdification date', null=True, verbose_name='Modification date')),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
            },
        ),
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, help_text='Enter a title', max_length=50, verbose_name='Title')),
                ('colour', models.CharField(blank=True, default=None, help_text='(Optional) Enter a Hexidecimal colour representation', max_length=7, null=True, verbose_name='Colour')),
                ('description', models.CharField(blank=True, default=None, help_text='(Optional) Enter a description', max_length=250, null=True, verbose_name='Description')),
                ('created', models.DateTimeField(editable=False, help_text='The creation date', verbose_name='Creation Date')),
                ('modified', models.DateTimeField(editable=False, help_text='The mdification date', null=True, verbose_name='Modification date')),
                ('delta', models.IntegerField(blank=True, default=None, help_text='(Optional) Enter a time delta in hours', null=True, verbose_name='Action Delta Hours')),
            ],
            options={
                'verbose_name': 'Priority',
                'verbose_name_plural': 'Priorities',
            },
        ),
        migrations.CreateModel(
            name='UploadModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now=True, null=True)),
                ('file_note', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('file_name', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('upload_location', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('file_title', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('date_deleted', models.DateTimeField(auto_now=True, null=True)),
                ('file_hash', models.CharField(blank=True, default=None, help_text='(Optional) Enter a File Hash', max_length=250, null=True, verbose_name='File Hash')),
                ('private', models.BooleanField(default=False, help_text='(Optional) Is Private', verbose_name='Private')),
                ('created', models.DateTimeField(editable=False, help_text='The creation date', verbose_name='Creation Date')),
                ('modified', models.DateTimeField(editable=False, help_text='The mdification date', null=True, verbose_name='Modification date')),
            ],
        ),
    ]
