# Generated by Django 2.0.3 on 2018-12-01 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authorisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Description')),
                ('created', models.DateTimeField(editable=False, verbose_name='Creation date and time')),
                ('modified', models.DateTimeField(editable=False, null=True, verbose_name='Modification date and time')),
                ('title', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Authorisation')),
                ('level', models.IntegerField(verbose_name='Level')),
                ('colour', models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='Colour')),
            ],
            options={
                'verbose_name': 'Authorisation',
                'verbose_name_plural': 'Authorisation',
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, default=None, max_length=5000, null=True, verbose_name='Note')),
                ('created', models.DateTimeField(editable=False, verbose_name='Creation date and time')),
                ('modified', models.DateTimeField(editable=False, null=True, verbose_name='Modification date and time')),
                ('private', models.BooleanField(default=False, verbose_name='Private')),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
            },
        ),
        migrations.CreateModel(
            name='UploadModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private', models.BooleanField(default=False, verbose_name='Private')),
                ('description', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Description')),
                ('created', models.DateTimeField(editable=False, verbose_name='Creation date and time')),
                ('modified', models.DateTimeField(editable=False, null=True, verbose_name='Modification date and time')),
                ('date_time', models.DateTimeField(auto_now=True, null=True)),
                ('file_note', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('file_hash', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('file_name', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('upload_location', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('file_title', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('date_deleted', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
