# Generated by Django 2.0.3 on 2018-12-08 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadmodel',
            name='description',
        ),
        migrations.AlterField(
            model_name='authorisation',
            name='colour',
            field=models.CharField(blank=True, default=None, help_text='(Optional) Enter a Hexidecimal colour representation', max_length=7, null=True, verbose_name='Colour'),
        ),
        migrations.AlterField(
            model_name='authorisation',
            name='created',
            field=models.DateTimeField(editable=False, help_text='The creation date', verbose_name='Creation Date'),
        ),
        migrations.AlterField(
            model_name='authorisation',
            name='description',
            field=models.CharField(blank=True, default=None, help_text='(Optional) Enter a description', max_length=250, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='authorisation',
            name='level',
            field=models.IntegerField(default=None, help_text='Enter a level', verbose_name='Level'),
        ),
        migrations.AlterField(
            model_name='authorisation',
            name='modified',
            field=models.DateTimeField(editable=False, help_text='The mdification date', null=True, verbose_name='Modification date'),
        ),
        migrations.AlterField(
            model_name='authorisation',
            name='title',
            field=models.CharField(default=None, help_text='Enter a title', max_length=50, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='note',
            name='created',
            field=models.DateTimeField(editable=False, help_text='The creation date', verbose_name='Creation Date'),
        ),
        migrations.AlterField(
            model_name='note',
            name='modified',
            field=models.DateTimeField(editable=False, help_text='The mdification date', null=True, verbose_name='Modification date'),
        ),
        migrations.AlterField(
            model_name='note',
            name='note',
            field=models.CharField(default=None, help_text='Enter a note', max_length=5000, verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='note',
            name='private',
            field=models.BooleanField(default=False, help_text='(Optional) Is Private', verbose_name='Private'),
        ),
        migrations.AlterField(
            model_name='uploadmodel',
            name='created',
            field=models.DateTimeField(editable=False, help_text='The creation date', verbose_name='Creation Date'),
        ),
        migrations.AlterField(
            model_name='uploadmodel',
            name='file_hash',
            field=models.CharField(blank=True, default=None, help_text='(Optional) Enter a File Hash', max_length=250, null=True, verbose_name='File Hash'),
        ),
        migrations.AlterField(
            model_name='uploadmodel',
            name='modified',
            field=models.DateTimeField(editable=False, help_text='The mdification date', null=True, verbose_name='Modification date'),
        ),
        migrations.AlterField(
            model_name='uploadmodel',
            name='private',
            field=models.BooleanField(default=False, help_text='(Optional) Is Private', verbose_name='Private'),
        ),
    ]
