# Generated by Django 2.0.3 on 2019-04-22 02:17

from django.db import migrations, models
import utils.models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadmodel',
            name='upload',
            field=models.FileField(default=1, help_text='The mdification date', upload_to=utils.models.user_directory_path, verbose_name='Modification date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='uploadmodel',
            name='date_deleted',
            field=models.DateTimeField(auto_now=True, help_text='The mdification date', null=True, verbose_name='Modification date'),
        ),
        migrations.AlterField(
            model_name='uploadmodel',
            name='date_time',
            field=models.DateTimeField(auto_now=True, help_text='The mdification date', null=True, verbose_name='Modification date'),
        ),
        migrations.AlterField(
            model_name='uploadmodel',
            name='deleted',
            field=models.BooleanField(default=False, help_text='The mdification date', verbose_name='Modification date'),
        ),
        migrations.AlterField(
            model_name='uploadmodel',
            name='file_name',
            field=models.CharField(blank=True, default=None, help_text='The mdification date', max_length=250, null=True, verbose_name='Modification date'),
        ),
        migrations.AlterField(
            model_name='uploadmodel',
            name='file_note',
            field=models.CharField(blank=True, default=None, help_text='The mdification date', max_length=250, null=True, verbose_name='Modification date'),
        ),
        migrations.AlterField(
            model_name='uploadmodel',
            name='file_title',
            field=models.CharField(blank=True, default=None, help_text='The mdification date', max_length=250, null=True, verbose_name='Modification date'),
        ),
        migrations.AlterField(
            model_name='uploadmodel',
            name='upload_location',
            field=models.CharField(blank=True, default=None, help_text='The mdification date', max_length=250, null=True, verbose_name='Modification date'),
        ),
    ]
