# Generated by Django 2.0.3 on 2018-12-08 05:11

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chainofcustody',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='chainofcustody',
            name='custody_receipt',
        ),
        migrations.RemoveField(
            model_name='chainofcustody',
            name='custody_receipt_label',
        ),
        migrations.RemoveField(
            model_name='chainofcustody',
            name='date_of_custody',
        ),
        migrations.RemoveField(
            model_name='chainofcustody',
            name='date_recorded',
        ),
        migrations.RemoveField(
            model_name='historicalchainofcustody',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='historicalchainofcustody',
            name='custody_receipt',
        ),
        migrations.RemoveField(
            model_name='historicalchainofcustody',
            name='custody_receipt_label',
        ),
        migrations.RemoveField(
            model_name='historicalchainofcustody',
            name='date_of_custody',
        ),
        migrations.RemoveField(
            model_name='historicalchainofcustody',
            name='date_recorded',
        ),
        migrations.AddField(
            model_name='chainofcustody',
            name='date_of_receipt',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 8, 5, 11, 16, 356859, tzinfo=utc), help_text='(Optional) Enter date of reciept', null=True, verbose_name='Date of Custody'),
        ),
        migrations.AddField(
            model_name='chainofcustody',
            name='receipt',
            field=models.CharField(blank=True, default=None, help_text='(Optional) Enter reciept number', max_length=50, null=True, verbose_name='Custody Receipt Number'),
        ),
        migrations.AddField(
            model_name='historicalchainofcustody',
            name='date_of_receipt',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 8, 5, 11, 16, 356859, tzinfo=utc), help_text='(Optional) Enter date of reciept', null=True, verbose_name='Date of Custody'),
        ),
        migrations.AddField(
            model_name='historicalchainofcustody',
            name='receipt',
            field=models.CharField(blank=True, default=None, help_text='(Optional) Enter reciept number', max_length=50, null=True, verbose_name='Custody Receipt Number'),
        ),
        migrations.AlterField(
            model_name='chainofcustody',
            name='assigned_by',
            field=models.ForeignKey(blank=True, help_text='(Optional) Select Chain Of Custody assigned by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chain_of_custody_assigned_by', to=settings.AUTH_USER_MODEL, verbose_name='Assigned By'),
        ),
        migrations.AlterField(
            model_name='chainofcustody',
            name='assigned_to',
            field=models.ManyToManyField(blank=True, help_text='(Optional) Select Chain Of Custody assigned to', related_name='chain_of_custody_assigned_to', to=settings.AUTH_USER_MODEL, verbose_name='Assigned To'),
        ),
        migrations.AlterField(
            model_name='chainofcustody',
            name='check_in',
            field=models.BooleanField(default=False, help_text='(Optional) Is the item recieved', verbose_name='Checked-In'),
        ),
        migrations.AlterField(
            model_name='chainofcustody',
            name='created',
            field=models.DateTimeField(editable=False, help_text='The creation date', verbose_name='Creation Date'),
        ),
        migrations.AlterField(
            model_name='chainofcustody',
            name='custodian',
            field=models.ForeignKey(blank=True, help_text='(Optional) Select the Chain Of Custody Custodian', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chain_of_custody_custodian', to=settings.AUTH_USER_MODEL, verbose_name='Evidence Custodian'),
        ),
        migrations.AlterField(
            model_name='chainofcustody',
            name='description',
            field=models.CharField(blank=True, default=None, help_text='(Optional) Enter a description', max_length=250, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='chainofcustody',
            name='modified',
            field=models.DateTimeField(editable=False, help_text='The mdification date', null=True, verbose_name='Modification date'),
        ),
        migrations.AlterField(
            model_name='chainofcustody',
            name='private',
            field=models.BooleanField(default=False, help_text='(Optional) Is Private', verbose_name='Private'),
        ),
        migrations.AlterField(
            model_name='evidencecategory',
            name='colour',
            field=models.CharField(blank=True, default=None, help_text='(Optional) Enter a Hexidecimal colour representation', max_length=7, null=True, verbose_name='Colour'),
        ),
        migrations.AlterField(
            model_name='evidencecategory',
            name='created',
            field=models.DateTimeField(editable=False, help_text='The creation date', verbose_name='Creation Date'),
        ),
        migrations.AlterField(
            model_name='evidencecategory',
            name='description',
            field=models.CharField(blank=True, default=None, help_text='(Optional) Enter a description', max_length=250, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='evidencecategory',
            name='modified',
            field=models.DateTimeField(editable=False, help_text='The mdification date', null=True, verbose_name='Modification date'),
        ),
        migrations.AlterField(
            model_name='evidencecategory',
            name='title',
            field=models.CharField(default=None, help_text='Enter a title', max_length=50, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='evidenceclassification',
            name='colour',
            field=models.CharField(blank=True, default=None, help_text='(Optional) Enter a Hexidecimal colour representation', max_length=7, null=True, verbose_name='Colour'),
        ),
        migrations.AlterField(
            model_name='evidenceclassification',
            name='created',
            field=models.DateTimeField(editable=False, help_text='The creation date', verbose_name='Creation Date'),
        ),
        migrations.AlterField(
            model_name='evidenceclassification',
            name='description',
            field=models.CharField(blank=True, default=None, help_text='(Optional) Enter a description', max_length=250, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='evidenceclassification',
            name='modified',
            field=models.DateTimeField(editable=False, help_text='The mdification date', null=True, verbose_name='Modification date'),
        ),
        migrations.AlterField(
            model_name='evidenceclassification',
            name='title',
            field=models.CharField(default=None, help_text='Enter a title', max_length=50, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='evidencepriority',
            name='colour',
            field=models.CharField(blank=True, default=None, help_text='(Optional) Enter a Hexidecimal colour representation', max_length=7, null=True, verbose_name='Colour'),
        ),
        migrations.AlterField(
            model_name='evidencepriority',
            name='created',
            field=models.DateTimeField(editable=False, help_text='The creation date', verbose_name='Creation Date'),
        ),
        migrations.AlterField(
            model_name='evidencepriority',
            name='description',
            field=models.CharField(blank=True, default=None, help_text='(Optional) Enter a description', max_length=250, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='evidencepriority',
            name='modified',
            field=models.DateTimeField(editable=False, help_text='The mdification date', null=True, verbose_name='Modification date'),
        ),
        migrations.AlterField(
            model_name='evidencepriority',
            name='title',
            field=models.CharField(default=None, help_text='Enter a title', max_length=50, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='evidencestatus',
            name='colour',
            field=models.CharField(blank=True, default=None, help_text='(Optional) Enter a Hexidecimal colour representation', max_length=7, null=True, verbose_name='Colour'),
        ),
        migrations.AlterField(
            model_name='evidencestatus',
            name='created',
            field=models.DateTimeField(editable=False, help_text='The creation date', verbose_name='Creation Date'),
        ),
        migrations.AlterField(
            model_name='evidencestatus',
            name='description',
            field=models.CharField(blank=True, default=None, help_text='(Optional) Enter a description', max_length=250, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='evidencestatus',
            name='modified',
            field=models.DateTimeField(editable=False, help_text='The mdification date', null=True, verbose_name='Modification date'),
        ),
        migrations.AlterField(
            model_name='evidencestatus',
            name='title',
            field=models.CharField(default=None, help_text='Enter a title', max_length=50, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='evidencestatusgroup',
            name='colour',
            field=models.CharField(blank=True, default=None, help_text='(Optional) Enter a Hexidecimal colour representation', max_length=7, null=True, verbose_name='Colour'),
        ),
        migrations.AlterField(
            model_name='evidencestatusgroup',
            name='created',
            field=models.DateTimeField(editable=False, help_text='The creation date', verbose_name='Creation Date'),
        ),
        migrations.AlterField(
            model_name='evidencestatusgroup',
            name='description',
            field=models.CharField(blank=True, default=None, help_text='(Optional) Enter a description', max_length=250, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='evidencestatusgroup',
            name='modified',
            field=models.DateTimeField(editable=False, help_text='The mdification date', null=True, verbose_name='Modification date'),
        ),
        migrations.AlterField(
            model_name='evidencestatusgroup',
            name='status',
            field=models.ManyToManyField(blank=True, help_text='Select Evidence Status', to='evidence.EvidenceStatus', verbose_name='Evidence Status'),
        ),
        migrations.AlterField(
            model_name='evidencestatusgroup',
            name='title',
            field=models.CharField(default=None, help_text='Enter a title', max_length=50, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='evidencetype',
            name='colour',
            field=models.CharField(blank=True, default=None, help_text='(Optional) Enter a Hexidecimal colour representation', max_length=7, null=True, verbose_name='Colour'),
        ),
        migrations.AlterField(
            model_name='evidencetype',
            name='created',
            field=models.DateTimeField(editable=False, help_text='The creation date', verbose_name='Creation Date'),
        ),
        migrations.AlterField(
            model_name='evidencetype',
            name='description',
            field=models.CharField(blank=True, default=None, help_text='(Optional) Enter a description', max_length=250, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='evidencetype',
            name='modified',
            field=models.DateTimeField(editable=False, help_text='The mdification date', null=True, verbose_name='Modification date'),
        ),
        migrations.AlterField(
            model_name='evidencetype',
            name='title',
            field=models.CharField(default=None, help_text='Enter a title', max_length=50, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='historicalchainofcustody',
            name='check_in',
            field=models.BooleanField(default=False, help_text='(Optional) Is the item recieved', verbose_name='Checked-In'),
        ),
        migrations.AlterField(
            model_name='historicalchainofcustody',
            name='created',
            field=models.DateTimeField(editable=False, help_text='The creation date', verbose_name='Creation Date'),
        ),
        migrations.AlterField(
            model_name='historicalchainofcustody',
            name='description',
            field=models.CharField(blank=True, default=None, help_text='(Optional) Enter a description', max_length=250, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='historicalchainofcustody',
            name='modified',
            field=models.DateTimeField(editable=False, help_text='The mdification date', null=True, verbose_name='Modification date'),
        ),
        migrations.AlterField(
            model_name='historicalchainofcustody',
            name='private',
            field=models.BooleanField(default=False, help_text='(Optional) Is Private', verbose_name='Private'),
        ),
        migrations.AlterField(
            model_name='historicalevidencecategory',
            name='colour',
            field=models.CharField(blank=True, default=None, help_text='(Optional) Enter a Hexidecimal colour representation', max_length=7, null=True, verbose_name='Colour'),
        ),
        migrations.AlterField(
            model_name='historicalevidencecategory',
            name='created',
            field=models.DateTimeField(editable=False, help_text='The creation date', verbose_name='Creation Date'),
        ),
        migrations.AlterField(
            model_name='historicalevidencecategory',
            name='description',
            field=models.CharField(blank=True, default=None, help_text='(Optional) Enter a description', max_length=250, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='historicalevidencecategory',
            name='modified',
            field=models.DateTimeField(editable=False, help_text='The mdification date', null=True, verbose_name='Modification date'),
        ),
        migrations.AlterField(
            model_name='historicalevidencecategory',
            name='title',
            field=models.CharField(default=None, help_text='Enter a title', max_length=50, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='historicalevidenceclassification',
            name='colour',
            field=models.CharField(blank=True, default=None, help_text='(Optional) Enter a Hexidecimal colour representation', max_length=7, null=True, verbose_name='Colour'),
        ),
        migrations.AlterField(
            model_name='historicalevidenceclassification',
            name='created',
            field=models.DateTimeField(editable=False, help_text='The creation date', verbose_name='Creation Date'),
        ),
        migrations.AlterField(
            model_name='historicalevidenceclassification',
            name='description',
            field=models.CharField(blank=True, default=None, help_text='(Optional) Enter a description', max_length=250, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='historicalevidenceclassification',
            name='modified',
            field=models.DateTimeField(editable=False, help_text='The mdification date', null=True, verbose_name='Modification date'),
        ),
        migrations.AlterField(
            model_name='historicalevidenceclassification',
            name='title',
            field=models.CharField(default=None, help_text='Enter a title', max_length=50, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='historicalevidencepriority',
            name='colour',
            field=models.CharField(blank=True, default=None, help_text='(Optional) Enter a Hexidecimal colour representation', max_length=7, null=True, verbose_name='Colour'),
        ),
        migrations.AlterField(
            model_name='historicalevidencepriority',
            name='created',
            field=models.DateTimeField(editable=False, help_text='The creation date', verbose_name='Creation Date'),
        ),
        migrations.AlterField(
            model_name='historicalevidencepriority',
            name='description',
            field=models.CharField(blank=True, default=None, help_text='(Optional) Enter a description', max_length=250, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='historicalevidencepriority',
            name='modified',
            field=models.DateTimeField(editable=False, help_text='The mdification date', null=True, verbose_name='Modification date'),
        ),
        migrations.AlterField(
            model_name='historicalevidencepriority',
            name='title',
            field=models.CharField(default=None, help_text='Enter a title', max_length=50, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='historicalevidencestatus',
            name='colour',
            field=models.CharField(blank=True, default=None, help_text='(Optional) Enter a Hexidecimal colour representation', max_length=7, null=True, verbose_name='Colour'),
        ),
        migrations.AlterField(
            model_name='historicalevidencestatus',
            name='created',
            field=models.DateTimeField(editable=False, help_text='The creation date', verbose_name='Creation Date'),
        ),
        migrations.AlterField(
            model_name='historicalevidencestatus',
            name='description',
            field=models.CharField(blank=True, default=None, help_text='(Optional) Enter a description', max_length=250, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='historicalevidencestatus',
            name='modified',
            field=models.DateTimeField(editable=False, help_text='The mdification date', null=True, verbose_name='Modification date'),
        ),
        migrations.AlterField(
            model_name='historicalevidencestatus',
            name='title',
            field=models.CharField(default=None, help_text='Enter a title', max_length=50, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='historicalevidencestatusgroup',
            name='colour',
            field=models.CharField(blank=True, default=None, help_text='(Optional) Enter a Hexidecimal colour representation', max_length=7, null=True, verbose_name='Colour'),
        ),
        migrations.AlterField(
            model_name='historicalevidencestatusgroup',
            name='created',
            field=models.DateTimeField(editable=False, help_text='The creation date', verbose_name='Creation Date'),
        ),
        migrations.AlterField(
            model_name='historicalevidencestatusgroup',
            name='description',
            field=models.CharField(blank=True, default=None, help_text='(Optional) Enter a description', max_length=250, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='historicalevidencestatusgroup',
            name='modified',
            field=models.DateTimeField(editable=False, help_text='The mdification date', null=True, verbose_name='Modification date'),
        ),
        migrations.AlterField(
            model_name='historicalevidencestatusgroup',
            name='title',
            field=models.CharField(default=None, help_text='Enter a title', max_length=50, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='historicalevidencetype',
            name='colour',
            field=models.CharField(blank=True, default=None, help_text='(Optional) Enter a Hexidecimal colour representation', max_length=7, null=True, verbose_name='Colour'),
        ),
        migrations.AlterField(
            model_name='historicalevidencetype',
            name='created',
            field=models.DateTimeField(editable=False, help_text='The creation date', verbose_name='Creation Date'),
        ),
        migrations.AlterField(
            model_name='historicalevidencetype',
            name='description',
            field=models.CharField(blank=True, default=None, help_text='(Optional) Enter a description', max_length=250, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='historicalevidencetype',
            name='modified',
            field=models.DateTimeField(editable=False, help_text='The mdification date', null=True, verbose_name='Modification date'),
        ),
        migrations.AlterField(
            model_name='historicalevidencetype',
            name='title',
            field=models.CharField(default=None, help_text='Enter a title', max_length=50, verbose_name='Title'),
        ),
    ]
