# Generated by Django 2.0.3 on 2018-07-22 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evidence',
            name='assigned_by',
        ),
        migrations.RemoveField(
            model_name='evidence',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='evidence',
            name='authorisation',
        ),
        migrations.RemoveField(
            model_name='evidence',
            name='category',
        ),
        migrations.RemoveField(
            model_name='evidence',
            name='chain_of_custody',
        ),
        migrations.RemoveField(
            model_name='evidence',
            name='classification',
        ),
        migrations.RemoveField(
            model_name='evidence',
            name='custodian',
        ),
        migrations.RemoveField(
            model_name='evidence',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='evidence',
            name='status',
        ),
        migrations.RemoveField(
            model_name='evidence',
            name='type',
        ),
        migrations.RemoveField(
            model_name='historicalevidence',
            name='assigned_by',
        ),
        migrations.RemoveField(
            model_name='historicalevidence',
            name='authorisation',
        ),
        migrations.RemoveField(
            model_name='historicalevidence',
            name='category',
        ),
        migrations.RemoveField(
            model_name='historicalevidence',
            name='chain_of_custody',
        ),
        migrations.RemoveField(
            model_name='historicalevidence',
            name='classification',
        ),
        migrations.RemoveField(
            model_name='historicalevidence',
            name='custodian',
        ),
        migrations.RemoveField(
            model_name='historicalevidence',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalevidence',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='historicalevidence',
            name='status',
        ),
        migrations.RemoveField(
            model_name='historicalevidence',
            name='type',
        ),
        migrations.AddField(
            model_name='chainofcustody',
            name='private',
            field=models.BooleanField(default=False, verbose_name='Private'),
        ),
        migrations.AddField(
            model_name='evidenceauthorisation',
            name='private',
            field=models.BooleanField(default=False, verbose_name='Private'),
        ),
        migrations.AddField(
            model_name='evidencecategory',
            name='private',
            field=models.BooleanField(default=False, verbose_name='Private'),
        ),
        migrations.AddField(
            model_name='evidenceclassification',
            name='private',
            field=models.BooleanField(default=False, verbose_name='Private'),
        ),
        migrations.AddField(
            model_name='evidencepriority',
            name='private',
            field=models.BooleanField(default=False, verbose_name='Private'),
        ),
        migrations.AddField(
            model_name='evidencestatus',
            name='private',
            field=models.BooleanField(default=False, verbose_name='Private'),
        ),
        migrations.AddField(
            model_name='evidencestatusgroup',
            name='private',
            field=models.BooleanField(default=False, verbose_name='Private'),
        ),
        migrations.AddField(
            model_name='evidencetype',
            name='private',
            field=models.BooleanField(default=False, verbose_name='Private'),
        ),
        migrations.DeleteModel(
            name='Evidence',
        ),
        migrations.DeleteModel(
            name='HistoricalEvidence',
        ),
    ]
