# Generated by Django 2.0.3 on 2018-12-08 05:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0002_auto_20181208_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chainofcustody',
            name='date_of_receipt',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='(Optional) Enter date of reciept', null=True, verbose_name='Date of Custody'),
        ),
        migrations.AlterField(
            model_name='historicalchainofcustody',
            name='date_of_receipt',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='(Optional) Enter date of reciept', null=True, verbose_name='Date of Custody'),
        ),
    ]
