# Generated by Django 2.0.3 on 2018-12-08 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0003_auto_20181208_1513'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chainofcustody',
            options={'verbose_name': 'Chain Of Custody', 'verbose_name_plural': 'Chain Of Custody'},
        ),
        migrations.AlterModelOptions(
            name='historicalchainofcustody',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Chain Of Custody'},
        ),
    ]
